### ISSUE TITLE
Make a subcommand to upload profiles (pyroscope upload)

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#100]
As I was working on #83 I figured it would be cool to be able to do something like:
```
printf "foo;bar 100\nfoo;baz 200\n" | pyroscope upload -from now-1m -until now
```

I think this would also enable faster adoption of other profilers.

---

It could also support a mode in which it chunks (10 second each) a stream of profiling data coming in that same kind of format.

---

There's already support for different profiling formats:
* https://github.com/pyroscope-io/pyroscope/blob/main/pkg/convert/parser.go#L20

---

Here's some documentation on agent / server communication:
![diagram](https://user-images.githubusercontent.com/662636/115311366-69bfbc80-a124-11eb-9891-8f94f9df0eac.png)

^ in this example `pyroscope exec` communicates with `pyroscope server`. For this issue we basically need to implement a way to upload profiling data via `pyroscope upload` instead of `pyroscope exec`

**Comment by Rperry2174** [comment]
closing in favor of #652 #601
