### ISSUE TITLE
users list not show

### ISSUE THREAD

**Issue by lpflpf** [pyroscope-io/pyroscope#1032]
request path /settings/users, and add some user, but cannot be show .  

maybe a ui bug,because i can get xhr return response.

**Comment by Rperry2174** [comment]
Hi @lpflpf thanks for reporting. Can you give us more info?

- Which version of Pyroscope are you using?
- What authentication are you using (I.e. internal, Google, gitlab)?
- Are all users missing or just one? 
- how did you create the user (api or via the ui)?

**Comment by lpflpf** [comment]
version: 0.14.0
authentication: internal
all user cannot be show. and i create user by ui

**Comment by Rperry2174** [comment]
Hi @lpflpf this should be fixed now in v0.15.2 (via #1048) let us know if you still have any issues. Thanks for reporting!
