### ISSUE TITLE
Display backend message when password fails to be changed

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#1034]
https://github.com/pyroscope-io/pyroscope/blob/352ed9fe70b92df1959afb8a78d355fd5c544012/webapp/javascript/redux/reducers/user.ts#L80-L86

The backend returns an array of errors, which should be displayed to the user.

I believe we can use `err instanceof RequestNotOkWithErrorsList` to return a list of errors, and `err instanceof RequestNotOkError` to display the string directly.  BTW these come from https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/services/base.ts#L10

**Comment by shaleynikov** [comment]
We actually handle that on password page 
https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/Settings/Security/ChangePasswordForm.tsx#L29-L51

Should we display same message as notification?

**Comment by eh-am** [comment]
I am having some other issues so I am not able to reproduce, but IIRC @petethepig had an issue where he was not able to change password due to the second one being different from the first one (just a typo), but the UI didn't actually tell THAT was the exact problem. Not

**Comment by eh-am** [comment]
Tried this and was not able to reproduce that issue! Closing it
