### ISSUE TITLE
client/agent: make client log level configurable

### ISSUE THREAD

**Issue by scbizu** [pyroscope-io/pyroscope#105]
Hi , there ! Thanks for writing such an awesome profiling platform ~

We try to integrate pyroscope go client into our Go codebase , but we found that the profile upload log is too frequent to find other logs (and the log itself is not important for the business developers) .

We know that we can set the `LOG_LEVEL` to our env to set the log level by ourselves , but things not goes easy , we also use logrus as our log framework , and this env will affect our business codebase.

As a workaround , can pyroscope agent pass the log level as an option into the `profiler.Config` , `WithLogLevel` for example . And thus we can wrap this option into our base codebase and do not export into the business codebase.

I can raise a PR to do this if you want some help ~

**Comment by scbizu** [comment]
I see #102 🤩

**Comment by petethepig** [comment]
I know it's annoying, we'll fix it soon, sorry!

**Comment by petethepig** [comment]
Addressed in #102
