### ISSUE TITLE
Add delays/exponential backoff when loading application names 

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#1052]
https://user-images.githubusercontent.com/6951209/164473399-c8468d52-54e2-4ce3-a1a1-37dc2b22a4f5.mp4

It seems we keep trying to load application names indefinitely. Most likely user has self profiling enabled, which means after few seconds there should be at least data from pyroscope itself. But we can't assume that.

Let's add at least some delay between requests and maybe a maximum amount of tries before giving up?

**Comment by petethepig** [comment]
Is it this repo or cloudstorage? If it's this repo then something is wrong... I don't think we should have reloads like this anywhere.
