### ISSUE TITLE
Update go to 1.18

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#1081]
One thing in particular I'd be interested to look at is the impact of this change:

> Go 1.17 [implemented](https://tip.golang.org/doc/go1.17#compiler) a new way of passing function arguments and results using registers instead of the stack on 64-bit x86 architecture on selected operating systems. Go 1.18 expands the supported platforms to include 64-bit ARM (GOARCH=arm64), big- and little-endian 64-bit PowerPC (GOARCH=ppc64, ppc64le), as well as 64-bit x86 architecture (GOARCH=amd64) on all operating systems. On 64-bit ARM and 64-bit PowerPC systems, benchmarking shows typical performance improvements of 10% or more.

**Comment by lizthegrey** [comment]
it's +10-15% performance on ARM. You don't want to miss out on it.

**Comment by petethepig** [comment]
Implemented in https://github.com/pyroscope-io/pyroscope/pull/1218
