### ISSUE TITLE
add pyspy nonblocking support

### ISSUE THREAD

**Issue by ediphy-dwild** [pyroscope-io/pyroscope#110]
is there any way to switch to pyspy nonblocking operation with an envvar or command line parameter?

when we launch our process with pyroscope, we see that our process hangs. from reading the py-spy docs it seems like this can happen when nonblocking mode is not used.

we are running on GKE (google kubernetes engine), with SYS_PTRACE enabled, kernel 4.19.112+, python 3.6.12, docker image pyroscope/pyroscope:0.0.25

from the limited profile we get before the process is automatically restarted, it seems that _select in a background thread is taking a lot of the profiled time, as if that is where the hang is (but this could be noise)

many thanks in advance

**Comment by petethepig** [comment]
Hi @ediphy-dwild 

We made non-blocking mode the default in the latest version (0.0.29) it should work much better now.

Let me know if it fixes the issue

**Comment by ediphy-dwild** [comment]
great to hear! will upgrade to latest and post back here - many thanks
