### ISSUE TITLE
Java JFR Flamegraph: Lambdas are being split

### ISSUE THREAD

**Issue by charlesverdad** [pyroscope-io/pyroscope#1129]
Hi, we are ingesting JFR files to Pyroscope from multiple ECS containers (replicas), tagging them with a `task_id`.

The frames under `Executor$` below are calls to the same method, but here we see that they are not being aggregated properly, with each call showing up in its own "icicle". I think this is because the method name's suffix `$$Lambda$xxxx/xxxxxxxxxx.run` is different for each container.

This problem disappears if I filter this by container (i.e. adding a `task_id` tag filter).

<img width="1322" alt="Screen Shot 2022-06-07 at 2 16 37 pm" src="https://user-images.githubusercontent.com/382186/172299288-72fc1aeb-4181-4b31-8d7e-f79fbe2b3dee.png">

It would be great if there's a way to combine these Lambda expressions, either at ingestion time or in the UI(?). I propose the former (maybe by just ignoring the `Lambda$.*` suffix) because I don't see any value in being able to split these.

Pyroscope server version: 0.17.1

**Comment by Rperry2174** [comment]
Thanks for reporting @charlesverdad we'll look into this as we've also seen this be kind of annoying to deal with. We'll keep you updated as we make progress

**Comment by Rperry2174** [comment]
this is fixed in [v0.19.0](https://github.com/pyroscope-io/pyroscope/releases/tag/v0.19.0) let us know how this works for you @charlesverdad !
