### ISSUE TITLE
Windows Server Support

### ISSUE THREAD

**Issue by steskalja** [pyroscope-io/pyroscope#115]
Will there eventually be Windows Server support? It is about half the market.

**Comment by petethepig** [comment]
We do plan to add support for Windows Server eventually.

**Comment by petethepig** [comment]
@steskalja We're gonna work on this soon, will track progress in #166

**Comment by autoantwort** [comment]
> [@steskalja](https://github.com/steskalja) We're gonna work on this soon, will track progress in [#166](https://github.com/grafana/pyroscope/issues/166)

#166 was closed without comment. So I guess no windows support is planned.
