### ISSUE TITLE
use ebpfagent to profile a service would hang up after few times

### ISSUE THREAD

**Issue by lingchengfenzi** [pyroscope-io/pyroscope#1171]
When I use ebpfagent to profile my service application, it would hang up after few upload times. My application has thousands threads. Because of bcc profile use 11 seconds would make too much overhead, I change the profile time to 1 second.

I add some print in pyroscope like this:

![reset](https://user-images.githubusercontent.com/25588133/174932919-af32faed-ea47-4c1f-943a-329272ef1a8b.png)

My command is:
`sudo -E ./pyroscope connect  --application-name my.test.program  --server-address https://******.com/ --spy-name ebpfspy  --pid <pid> --log-level debug`

And it hang up after print "9999999999999!"
![hang](https://user-images.githubusercontent.com/25588133/174933214-ed9290ab-3e4e-4753-bcad-055e83273e3b.png)

The OS is Centos 7.4 and the kernel is linux 4.18.

**Comment by Rperry2174** [comment]
hi @lingchengfenzi this should be fixed now. If you run into this issue again please let us know!

**Comment by lingchengfenzi** [comment]
Yes, it is fixed now. Thanks!
