### ISSUE TITLE
Feature: support environments filter application

### ISSUE THREAD

**Issue by Ackerr** [pyroscope-io/pyroscope#118]
Most of our projects has multiple environments like test and production. Now we create multiple app by one project. I think If use env, it will be clean and tidy. 

like Sentry:

![image](https://user-images.githubusercontent.com/35414361/110745669-94da0500-8276-11eb-8e3f-9de3b842c392.png)

**Comment by petethepig** [comment]
Good idea. I know it's not the same, but for now you could create different application names for each environment, e.g:
* `app-name.production`
* `app-name.development`

**Comment by Ackerr** [comment]
Thanks for your reply. Yeah, that's what I'm doing now.

And another question：how to delete a discard app?

**Comment by petethepig** [comment]
@Ackerr That's a feature we should add soon :)

I created an issue: https://github.com/pyroscope-io/pyroscope/issues/119
