### ISSUE TITLE
Find new terms for "left" and "right" for diff flamegraphs

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1181]
Currently when looking at diff flamegraphs we talk about "left" and "right" flamegraphs, which I think is less helpful then what those flamegraphs actually are. For example, if you use flamegraph.com and embed a flamegraph you get something that looks like this:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/23323466/175961719-92e56ee1-57fd-45e2-ae7e-f10cb9e341ee.png">

here are some other options:
- "left" --> original and "right" --> "comparison"
- "left" --> base and "right" --> "comparison"
- "left" --> old and "right" --> "new" 
- etc

**Comment by eh-am** [comment]
Makes total sense, I am only against old/new, because technically you can compare the other way around (new as the base and old as the comparison)

**Comment by Rperry2174** [comment]
closed in #1208
