### ISSUE TITLE
Requesting a setting to disable the ability to export to flamegraph.com

### ISSUE THREAD

**Issue by be-hase** [pyroscope-io/pyroscope#1186]
pyroscope is very useful.
I am thinking of introducing it in my work.

I would like to plug the export function to framegraph.com. I don't want to send any code-related information to the outside world.

I hope you will consider this.

**Comment by eh-am** [comment]
Hey @be-hase, thank you!

That's in our roadmap (https://github.com/pyroscope-io/pyroscope/issues/1119), it should not be too difficult. I will try to work on it ASAP.

But keep in mind people would still able to export (pprof/html/json/png) via the dropdown
![image](https://user-images.githubusercontent.com/6951209/176332781-6806c0f5-3d8f-45d6-8c40-f030ad1caf5f.png). Is that ok for you?

**Comment by be-hase** [comment]
Thank you very much.
Yes, if you can make it look like that screenshot, it should be fine.

BTW, I am currently preventing the export by setting the DNS of `flamegraph.com` to localhost as a workaround. Haha.

```yaml
# K8s Pod setting

...

hostAliases:
  - ip: "127.0.0.1"
    hostnames:
      - "flamegraph.com"
```
