### ISSUE TITLE
Frontend Tags Bug

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#1192]
Recorded an example:

https://user-images.githubusercontent.com/662636/176555890-d20a9f9d-1da0-4544-94ae-3e68c12c56d4.mp4

Basically, the issue is that sometimes the flamegraph doesn't update, even though I edit tags.

**Comment by Rperry2174** [comment]
@petethepig how do we recreate this issue?

**Comment by petethepig** [comment]
To reproduce, 

1. first run this script. It will create an app `broken-tags-app.cpu` with two tags: foo=bar and foo=baz

```bash

curl -X POST \
  --data 'foo;bar 100' \
  'http://localhost:4040/ingest?name=broken-tags-app.cpu%7Bfoo%3Dbar%7D&units=samples&sampleRate=100&from=1657046510&until=1657046520&spyName=pyspy&format=collapsed'

curl -X POST \
  --data 'foo;baz 100' \
  'http://localhost:4040/ingest?name=broken-tags-app.cpu%7Bfoo%3Dbaz%7D&units=samples&sampleRate=100&from=1657046510&until=1657046520&spyName=pyspy&format=collapsed'
```

2. Next open pyroscope http://localhost:4040/?query=broken-tags-app.cpu%7Bfoo%3D%22baz%22%7D&from=1657046438&until=1657046558

3. Switch between foo=bar and foo=baz — data won't get updated.

---

I think the problem is that timeline is the same for both profiles and somewhere in the code maybe it checks if timelines are different before rendering — and because they are the same it doesn't render new data.
