### ISSUE TITLE
ERRO[xxx] Direct upload queue is full, dropping a profile

### ISSUE THREAD

**Issue by dreamlu** [pyroscope-io/pyroscope#120]
ubuntu 20.04

go 1.15.8

![image](https://user-images.githubusercontent.com/21306894/110771477-80f1cb80-8295-11eb-9fe7-be74e151de70.png)

this error appear when i start the pyroscope server a few minutes

every time I exec `docker restart pyroscope`, it will be right, a few minutes it will be error and see nothing in the brower

ps： thanks for the useful project

**Comment by petethepig** [comment]
It's fixed in the latest release I think.

**Comment by dreamlu** [comment]
thanks, it's fixed
