### ISSUE TITLE
Implement delete app functionality as an HTTP endpoint

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#1223]
Currently it's only possible via the admin command.

We should add this functionality to the HTTP controller. We should make it so that it requires authentication. If there's no authentication mechanisms set up on the server it should return an error.

**Comment by eh-am** [comment]
Maybe we could even use the same admin server?  https://github.com/pyroscope-io/pyroscope/blob/main/pkg/admin/server.go#L42

**Comment by petethepig** [comment]
done in https://github.com/pyroscope-io/pyroscope/commit/b82f42625f5ee80fad9701d1abd2e0b059aee46c
