### ISSUE TITLE
Add more functionality to tooltip right-click menu

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1235]
Note: This should probably be done (in separate prs) but around same time as #1217 and #1234 
Right now when you right click there's only one option in the tooltip which is to "Focus on subtree". I think we should do two things:

1. Add more functionality to this right-click menu for popular actions that users might want to do
2. rename this "focus on subtree" to something more intuitive (what does "focus" mean, what is a "subtree"?) 
<img width="1512" alt="Screen Shot 2022-07-10 at 7 10 46 PM" src="https://user-images.githubusercontent.com/23323466/178175896-79d18d90-468c-42a4-a385-6bb70f32d4cd.png">

## New right-click menu functionality
- [ ] "Copy function name": copies the function name to your clipboard
- [ ] "Highlight similar nodes": highlights all nodes with the same name (i.e. in the picture above) 

## Renaming the "Focus on subtree" option
- [ ] "hide nodes above": does what currently "focus on subtree" does

What "focus on subtree" really means is either:
- **hide nodes above**
- collapse nodes above
- hide parent nodes
- collapse parent nodes

I think we should go with "collapse nodes above" because I think it explains more clearly what is about to happen without user's needing to know what a "subtree" is or what "focus" actually means (i.e. highlight vs collapse)

fwiw here's what is used in google sheets:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/23323466/178176609-ae4fbd49-2b22-4df1-aba6-f1f6ce5100b5.png">

## Adding icons
We could potentially also add icons for all of the items to make this menu look even nicer:

### Focus on subtree
[Fontawesome source ](https://fontawesome.com/search?q=focus&s=solid%2Cbrands)

Option A: <img width="34" alt="image" src="https://user-images.githubusercontent.com/23323466/178177436-8ad006d4-7051-4b91-873c-c27ae40833a2.png">

Option B: <img width="128" alt="image" src="https://user-images.githubusercontent.com/23323466/178177363-834bc854-2e1d-4401-999c-861c18b810c5.png">

Option C: <img width="114" alt="image" src="https://user-images.githubusercontent.com/23323466/178177383-a1e62ded-c6a1-4217-8cdb-e9f54041371a.png">

### Reset view 
<img width="100" alt="image" src="https://user-images.githubusercontent.com/23323466/178177573-98988eae-c38f-4300-8959-7b0e67de1c1d.png">

### Copy function name
<img width="97" alt="image" src="https://user-images.githubusercontent.com/23323466/178177628-2cedb883-99e2-40a2-aa0d-5ca5127e33bd.png">

### Highlight similar nodes
<img width="117" alt="image" src="https://user-images.githubusercontent.com/23323466/178177687-43a1a05b-c991-4e56-8ce5-857548ed7acf.png">

**Comment by eh-am** [comment]
There's already an icon for `Focus on subtree` in the toolbar
![image](https://user-images.githubusercontent.com/6951209/178567328-8b6eae5c-2916-43a1-983f-717344e6eda6.png)

So if we gonna add a icon to the context menu, it should either be the same, or we should update in both places

**Comment by Rperry2174** [comment]
closed in #1259
