### ISSUE TITLE
Issues running with jest + react + tsx files (error happened while parsing request body)

### ISSUE THREAD

**Issue by louisgjohnson** [pyroscope-io/pyroscope#1238]
Howdy! 

I'm trying to profile some frontend tests that are written in typescript, I keep getting this error:
` error happened while parsing request body`

I'm wondering if that's actually something this project supports or I'm using the wrong tool?

I'm also getting seg faults which seems concerning as well:
`nodejs/npm: line 14:  2471 Segmentation fault      "$basedir/node" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"`

these test also take about 30s to complete(hence the profiling)

**Comment by Rperry2174** [comment]
Thank you for reporting @louisgjohnson we'll take a look and see if it's a quick fix or not and get back to you

**Comment by louisgjohnson** [comment]
Thanks @Rperry2174 i can try and make a small reproducible repo if that helps and I’ll also try and attach more info about my issue, I was just a bit rushed yesterday when I raised it

**Comment by eh-am** [comment]
Just a heads up, we implemented a way to track ci executions (https://pyroscope.io/docs/ci/). For node it works pretty much how I explained above, but there's an [example here](https://github.com/pyroscope-io/ci/tree/main/examples/nodejs/jest) if you want to try.
