### ISSUE TITLE
Don't truncate app names

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#1265]
As the screenshot shows, it's important to be able to see the entire app name.

<img width="701" alt="Screen Shot 2022-07-14 at 14 31 43" src="https://user-images.githubusercontent.com/6951209/179046450-8c0bfb42-83d7-4d9d-b22f-2b3a85429bd7.png">

**Comment by Rperry2174** [comment]
FYI for whoever picks up I think the proper file is here: https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/AppSelector/SelectorModal.module.scss

**Comment by Trevy05** [comment]
Do you think this can be helped by adjusting the overflow? If so I would like to pick this issue up.

**Comment by eh-am** [comment]
Not sure TBH, @pavelpashkovsky any thoughts?

**Comment by eh-am** [comment]
@pavelpashkovsky and I discussed a little bit in private:

Pavel said that:
> I would say that setting free width for the second column covers 99.99% cases. No even need to set max-width.

So I think we could go with a "use as much space as possible" approach. That being said, I think we still need a max-width, in the case there's `a.really.long.app.name.for.some.really.good.reason`
