### ISSUE TITLE
Interacting with the table is slow

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#1308]
I tried to mouse the mouse right after clicking to display the slowness.
https://user-images.githubusercontent.com/6951209/180872216-e81281b7-7732-4cc2-8f69-136f93c9ad28.mp4

Flamegraph for reference
https://flamegraph.com/share/43b706b6-0c57-11ed-b763-eeb2a737e822

**Comment by petethepig** [comment]
it seems to be working faster in pyroscope itself, right?

**Comment by eh-am** [comment]
Nvm can't reproduce consistently
