### ISSUE TITLE
Handle errors when flamegraph.com responds with non 2xx

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#1312]
https://github.com/pyroscope-io/pyroscope/blob/main/pkg/server/export.go#L23

eg https://stackoverflow.com/a/55210335

**Comment by Gookuruto** [comment]
Should we just pass handler with given code like this: 

```
if resp.StatusCode < 200 || resp.StatusCode >= 300 {

			w.WriteHeader(resp.StatusCode)
		} else {
			w.WriteHeader(http.StatusOK)
		}
```
 or raise error with message that code is not succes?

**Comment by eh-am** [comment]
Good point, I think we can return whatever flamegraph.com returned (including the body).
