### ISSUE TITLE
Add support for uploading pprof and collapsed format in adhoc mode

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1317]
currently adhoc only supports uploading pyroscope JSON files, but we should make it so that it supports collapsed format and pprof format similar to [flamegraph.com](https://flamegraph.com/). 

Currently, iirc the uploaded flamegraph does not "touch" the backend. In order to implement this properly the steps will likely be something like:

- Create an endpoint that converts from X format to json
- connect it to the frontend
- render the json

**Comment by eh-am** [comment]
I think it may be easier to just update the existing endpoint to take any arbitrary data, similar to flamegraph.com?

Something like this
https://github.com/pyroscope-io/pyroscope/blob/main/pkg/adhoc/server/model.go#L42
```
converter, err := model.Converter()
fb, err := converter(m.Profile, name, u.maxNodes)
```
