### ISSUE TITLE
Flamegraph is squeezed in adhoc comparison UI

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#1333]
![image](https://user-images.githubusercontent.com/6951209/182231565-cb695f81-9c8d-4b0b-b452-0341ade86d2d.png)

**Comment by eh-am** [comment]
There's a `panesOrientation="vertical"` property we can use.

**Comment by Rperry2174** [comment]
yeah I don't think "both" should be an option here on comparison page
