### ISSUE TITLE
Improve UI of Adhoc drag and drop

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1334]
Currently the adhoc drag and drop has a lot of text and just looks generally messy. 

![image](https://user-images.githubusercontent.com/23323466/182233628-f3451d9b-8182-45f6-b0f8-d81ae17dfa60.png)

We should copy the design from flamegraph.com and make it look closer to this:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/23323466/182233666-160c09de-9078-4516-b4b8-15104938f7c4.png">

<img width="824" alt="image" src="https://user-images.githubusercontent.com/23323466/182233752-11fe3654-58d4-4a30-87b1-f3af8965a187.png">

**Comment by eh-am** [comment]
Also having a drop-down for thr user to tell which language/unit if uploaded manually would be nice

**Comment by pavelpashkovsky** [comment]
>Also having a drop-down for thr user to tell which language/unit if uploaded manually would be nice

@eh-am Can you please explain more about possible UI logic of dropdown

**Comment by pavelpashkovsky** [comment]
@eh-am, @Rperry2174 hey guys, as I understand Save button and Upload button have have same purpose
![image](https://user-images.githubusercontent.com/7372044/184343356-71422941-6647-4d82-b99a-e4e83a3afde8.png)

- should I adjust styles Save button as well to get it similar to Upload button in flamegraph.com?
- I copied styles from flamegraph.com to **Select a file** button, is it correct? I mean now this button isn't in Pyroscope style strictly (different size, padding, color). should I maybe just adopt some of the Pyroscope buttons?

**Comment by Rperry2174** [comment]
yeah all of the colors should be colors that we already have in [variables.css](https://github.com/pyroscope-io/pyroscope/blob/main/webapp/sass/variables.css)

(the current color in the screenshot also does not match the UI -- everything else about the style looks good though!
