### ISSUE TITLE
Add warning / mechanism for supporting older Typescript versions for Flamegraph

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1346]
In #1339 we made some changes to be able to support older typescript version with our flamegraph component (particularly for [Jaeger](https://github.com/jaegertracing/jaeger-ui/issues/390) usage in this case).. 

We should come up with a way to either alert us in CI if we use a Typescript feature that is not supported in typescript 3 or a way to convert typescript 4 to typescript 3 

This may be an option: https://github.com/sandersn/downlevel-dts

**Comment by eh-am** [comment]
Implemented in https://github.com/pyroscope-io/pyroscope/pull/1348
