### ISSUE TITLE
brew install Error: pyroscope: SHA256 mismatch

### ISSUE THREAD

**Issue by bineyond** [pyroscope-io/pyroscope#1378]
macOS 12.5  86

![fbb468883382e0fa](https://s3.bmp.ovh/imgs/2022/08/10/fbb468883382e0fa.png)

**Comment by petethepig** [comment]
@bineyond Thanks for reporting, we'll look into this soon!

**Comment by petethepig** [comment]
Hi @bineyond — we fixed the issue, there was a bug in our release script, we fixed it and you should be able to install pyroscope from homebrew now.

Let me know if there's still any issues!

**Comment by Rperry2174** [comment]
confirmed it's working now:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/23323466/184211475-51db60ea-e34c-476a-aea5-cca699e0d47e.png">
