### ISSUE TITLE
Add Support for Pyroscope Panel in Explore Tab

### ISSUE THREAD

**Issue by zhzure** [pyroscope-io/pyroscope#1381]
hi, appreciate for this amazing repo!
there is some problem when i try to link pyroscope with loki, but when i click `Tag link`, it seems can not auto fill `Query` like:
![oOmI8GBCBe](https://user-images.githubusercontent.com/107018432/183888980-c7cc91e0-09b8-4d50-89d7-54129e9bbde6.jpg)

and even if i using the right `profile_id` execute query, there is only data but flame graph
![image](https://user-images.githubusercontent.com/107018432/183890600-35acb7ab-0c1b-43f3-b3a2-27ffd47c8cea.png)

- grafana version
`v8.2.3`
- datasource plugin
`v1.1.0`
- panel plugin
`v1.1.0`
- loki setting
![o81lqT6D89](https://user-images.githubusercontent.com/107018432/183890689-10f499df-6441-4f7e-9d62-f71b25a8f981.jpg)

**Comment by Rperry2174** [comment]
hi @zhzure sorry for the inconvenience here, but somehow it got lost in the documentation that our example application which shows this functionality actually uses a fork of Grafana. 

The difference between the two is that the main Grafana branch does not allow for custom plugins (i.e. the flamegraph visualization) inside of the explore tab. 

We reached out to grafana and will create an issue to hopefully see if/how we can get this merged upstream

**Comment by zhzure** [comment]
> hi @zhzure sorry for the inconvenience here, but somehow it got lost in the documentation that our example application which shows this functionality actually uses a fork of Grafana.
> 
> The difference between the two is that the main Grafana branch does not allow for custom plugins (i.e. the flamegraph visualization) inside of the explore tab.
> 
> We reached out to grafana and will create an issue to hopefully see if/how we can get this merged upstream

thanks so much, appreciate !
integration with loki in grafana is really useful, hopefully it comes out soon!

**Comment by Rperry2174** [comment]
adding here that there is another effort in progress in Grafana that may help with this: 
https://github.com/grafana/grafana/pull/52057
