### ISSUE TITLE
Put name of service in title bar for better navigation

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1394]
Currently when navigating around Pyroscope the title bar remains constant and makes it so that in the history bar, you see a list that just says:

- pyroscope
- pyroscope
- pyroscope
- pyroscope 

instead of 
- pyroscope - explore
- pyroscope - diff 
- pyroscope - single view 

i.e. here grafana adds name of the dashboard to the title so that I can easily find it in history:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/23323466/184410931-9f288965-d6fe-40f9-b079-d2392208a8a3.png">

**Comment by eh-am** [comment]
I guess would be nice to also have the app name in the title, right?

**Comment by Rperry2174** [comment]
#1397
