### ISSUE TITLE
Explore timeline should have plus for icon

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1400]
On regular timelines there is a plus to indicate that the timeline can be interacted with. We should add this to the explore timeline as well. 

https://user-images.githubusercontent.com/23323466/184523765-a986ead5-469f-4a27-bbb2-b802fb436d7d.mov

we should also remove this circle until we add a tooltip in the timeline chart:
<img width="104" alt="image" src="https://user-images.githubusercontent.com/23323466/184523934-61bc0c0b-a925-4cf7-97be-916d75d6ef66.png">

We should also decrease the width of these lines because when there are a lot of them it gets harder to see

**Comment by eh-am** [comment]
I think may be time to discuss splitting the component into 2 different ones: one for single/comparison/diff and another for Tag explorer. It seems functionality is already too different.

**Comment by Rperry2174** [comment]
I'm fine with that, but I assume think this is just a setting somewhere. I think all timelines should have the same functionality in this case
