### ISSUE TITLE
Add apps page to the frontend

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#1416]
We need a page that would list all apps and have delete buttons. It should go under Settings. The route should be `/settings/apps`.

For now we should just make it a table with all the apps and one button (delete). We should make it look similar to other similar pages, e.g `/settings/users`. I know @dogfrogfog is working on a unified table component, it's a good idea to use that one here.

Regarding the backend. We have 2 API endpoints, one for listing apps:
```
GET /api/apps
```

One for deleting apps, it requires a `DELETE` method and takes a JSON with one field (`name`):
```
DELETE /api/apps
{
  "name": "pyroscope.server.cpu"
}
```

These routes are authentication protected, so to use them, run pyroscope with the following arguments:
```
PYROSCOPE_AUTH_INTERNAL_ENABLED=true make dev
```

You can then log into pyroscope using `admin/admin` combination.

**Comment by eh-am** [comment]
Let's not forget to add a warning/confirmation when deleting apps. Similar to
https://github.com/pyroscope-io/pyroscope/blob/main/pkg/admin/cli.go#L62-L75

**Comment by Rperry2174** [comment]
completed in #1424
