### ISSUE TITLE
Makefile rule build-release fails when GOPATH contains multiple directories

### ISSUE THREAD

**Issue by AulonSal** [pyroscope-io/pyroscope#142]
Rule build-release depends on rule embedded-assets:
https://github.com/pyroscope-io/pyroscope/blob/a94aca370330143920ae31472a3b27001924bbca/Makefile#L67-L69

According to `go help gopath`:
```
The GOPATH environment variable lists places to look for Go code.
On Unix, the value is a colon-separated string.
On Windows, the value is a semicolon-separated string.
On Plan 9, the value is a list.
```
Thus the rule fails when there is more than one directory in GOPATH as line 69 evaluates to `/path/1:/path/2/bin/pkger -o pkg/server`

**Comment by AulonSal** [comment]
Not fixed, pkger is in path/bin for a path in $GOPATH, adding $GOPATH to $PATH won't put it in path, and it will instead always fail now.

**Comment by petethepig** [comment]
@AulonSal oh yeah, you're right. What do you is the best solution here? 

I can think of 2 ways we could handle this:

* add `/bin` to each path in GOPATH in this Makefile
* I recently added this [pinned-tool.sh](https://github.com/pyroscope-io/pyroscope/blob/main/scripts/pinned-tool.sh) wrapper  — we could use it here as well.

basically the idea with it is that you'd run it like this:
```
scripts/pinned-tool.sh github.com/markbates/pkger -o pkg/server
```

and the script picks up the exact location of the pkger version described in `go.mod`

**Comment by AulonSal** [comment]
The second approach results in:
```bash
scripts/pinned-tool.sh github.com/markbates/pkger -o pkg/server
go run: cannot run non-main package
```

**Comment by petethepig** [comment]
@AulonSal Right... that's because `pkger` main package is in `cmd/pkger`

Okay, new plan. What if we changed the `scripts/pinned-tool.sh` to just echo the path to the module:
```
#!/bin/bash
echo "$(go list -m -f '{{.Dir}}' $1)"
```

And then we could run the script like this:
```
go run "$(scripts/pinned-tool.sh github.com/markbates/pkger)/cmd/pkger" -o pkg/server
```

---

I tested it on my setup and it works.

**Comment by AulonSal** [comment]
Yeah, that works for me too.

**Comment by petethepig** [comment]
@AulonSal I updated the [Makefile](https://github.com/pyroscope-io/pyroscope/blob/main/Makefile#L67-L73)

**Comment by AulonSal** [comment]
Thanks.
