### ISSUE TITLE
Make <CollapseBox /> component 

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1421]
In a page like the tag explorer, sometimes you want to collapse this box to hide the information inside (and see more of the flamegraph at the same time as the timeline. 

Open
![boc_collapse_open_00-01](https://user-images.githubusercontent.com/23323466/185300967-a0b89d34-e6a0-4b41-8007-5bb3df99cddc.png)

Closed
![boc_collapse_closed_00-01](https://user-images.githubusercontent.com/23323466/185301361-9c37afbe-11d8-49b4-9dbe-d0f8e47f01a2.png)

We should make it so that you can hover over a panel, like the "Descriptive Statistics" panel and the arrow will appear similar to this video, but instead of opening a dropdown the arrow can open or close the panel 

https://user-images.githubusercontent.com/23323466/185299368-df52ec7a-0b08-440a-81f6-f6deb118e8ba.mov

~We could probably enable this feature for the `<Box/>` component via a parameter~
We should create a new component similar to `<Box/>`called <CollapseBox /> that collapses

**Comment by eh-am** [comment]
I am thinking a `CollapseBox` component instead, that wraps the `Box` one :)

Reason is that not all boxes can just be collapsible straight way, one example from your screenshot is that a title is now required: 
![image](https://user-images.githubusercontent.com/6951209/185412420-c265ff3c-5ad0-4d7f-8174-1c350081066b.png)

Which is much cleaner to maintain if there's a component with those specific requirements.

**Comment by Rperry2174** [comment]
Updated title!
