### ISSUE TITLE
Comparison dropdown in Tag Explorer looks weird

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#1445]
https://user-images.githubusercontent.com/6951209/186762393-d6c812d5-d7b4-451f-864e-478369e8fde2.mp4

It should scroll just like the application dropdown
![image](https://user-images.githubusercontent.com/6951209/186762604-6741c765-8b15-418e-a6ec-2140fee1796d.png)

**Comment by Rperry2174** [comment]
closed in #1449
