### ISSUE TITLE
my app can not read env after pyroscope exec

### ISSUE THREAD

**Issue by Ehco1996** [pyroscope-io/pyroscope#147]
i found a strange situation that if i use ` pyroscope exec` to run some python scripts

in my own scripts can't read system env

anyone could help?

**Comment by Ehco1996** [comment]
To reprocude

test.py
```python
import os
print(os.getenv("SS_LOG_LEVEL"))
```

`export SS_LOG_LEVEL=debug`

when we run `python test.py` we get `debug`

but when we run `pyroscope exec python test.py` we get`none`

**Comment by petethepig** [comment]
Try adding `-E` flag to `sudo`:
```bash
sudo -E pyroscope exec python test.py
```

By default sudo drops those environment variables. We do have this on some pages in the docs, but not everywhere.

Thanks for bringing this up, we'll update the docs!

**Comment by Ehco1996** [comment]
@petethepig 

thanks for you reply，but my app running in the container without  `sudo`

so i don't know where to pass `-E` flag
