### ISSUE TITLE
Show percentages based on values for the same time period, not all time

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#1487]
We have this tooltip on explore page:
![Screen Shot 2022-09-09 at 5 28 15 PM](https://user-images.githubusercontent.com/662636/189461433-9d8018f8-b686-4f26-82c8-434bd3813903.png)

Currently it shows percentages but it looks like they are calculated using all values across time. Instead it should only take into consideration values for the time "selected". 

For example, for the screenshot above `eu-north` should show 100% because that's the only line with a value higher than 0.

For the screenshot below is should have eu-north be at `10%`, because `0.01` is 10% of `0.04+0.01+0.05 = 0.1`
![Screen Shot 2022-09-09 at 5 30 50 PM](https://user-images.githubusercontent.com/662636/189461513-60ad154c-3f57-4bdc-83a0-db1a41f05dc1.png)

**Comment by Rperry2174** [comment]
closed in #1631
