### ISSUE TITLE
Create plugin for annotations

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1495]
In #1489 we started adding annotations, which for now are a simple line using the built-in feature in flot library. 

Eventually we would like to switch from using the built-in functionality to using a custom plugin so that we can make fancy / more informative annotations such as these:

![mockup_annotations_00](https://user-images.githubusercontent.com/23323466/189971251-9f036972-ee6e-42fe-a842-e26b0fd20a00.png)

With the biggest difference being that different types of annotations will show a different icon.

cc @eh-am

**Comment by eh-am** [comment]
Another thing is that flot doesn't have a `z-index` concept, so sometimes it's draw underneath other stuff:
![image](https://user-images.githubusercontent.com/6951209/189979581-38d94b96-f402-491c-ab99-e56def816c69.png)

With a plugin we can control when to add these markings (ie after `drawSeries`) http://www.flotcharts.org/flot/API/
