### ISSUE TITLE
Very different results from Go's built-in pprof: all goroutines vs active goroutines?

### ISSUE THREAD

**Issue by mrowland7** [pyroscope-io/pyroscope#152]
Hey, I've been trying out Pyroscope the past few days and it's pretty cool! I noticed one odd thing with the Go integration - the results it gives are quite different from the ones using Go's built-in [pprof](https://golang.org/pkg/net/http/pprof/).

Pyroscope:
<img width="1955" alt="Screen Shot 2021-04-07 at 5 27 12 PM" src="https://user-images.githubusercontent.com/1819447/114036127-cb8f4500-984d-11eb-820e-86051dce7dc6.png">

Built-in:
<img width="2596" alt="Screen Shot 2021-04-08 at 9 37 26 AM" src="https://user-images.githubusercontent.com/1819447/114036609-38a2da80-984e-11eb-9075-60236c6a4e88.png">

The service I've profiled is a little unusual: it makes heavy use of goroutines. Each goroutine gets a task to read some files from AWS S3 and then do some computation on them, so using many goroutines lets the CPU not get blocked waiting for downloads to complete.

My suspicion is that this difference is because Pyroscope checks the stack frame of _every_  goroutine, not the ones that are actually running on the CPU at the time.

Perhaps https://github.com/pyroscope-io/pyroscope/pull/146 will fix this?

**Comment by petethepig** [comment]
Yes, the current implementation will show certain stacktraces even though the application is just waiting for IO. One way to think about it is this is wall time profiling and `pprof` is CPU time only profiling.

We've got similar feedback before and the idea behind #146 is that it will improve this. We're currently experimenting with different ways of getting the profiling data and we're most likely going to switch the go profiler to use `pprof`. We'll probably also leave the ability to use the current implementation as it can be useful sometimes to know when your app is waiting for IO.

@mrowland7 I'll let you know once we finalize the changes in #146

**Comment by mrowland7** [comment]
Saw this is fixed in `v0.0.30`, exciting!
