### ISSUE TITLE
Expected overhead of Pyroscope in Go?

### ISSUE THREAD

**Issue by mrowland7** [pyroscope-io/pyroscope#153]
Hey, in the process of researching https://github.com/pyroscope-io/pyroscope/issues/152, I took a profile with Go's built-in `pprof` tool. I noticed that the snapshotting process takes ~13% of CPU time for our already-fairly-busy service. 

<img width="2586" alt="Screen Shot 2021-04-08 at 9 48 21 AM" src="https://user-images.githubusercontent.com/1819447/114038150-9e439680-984f-11eb-87c1-03a12afc2b51.png">

Is this about what's expected? If so - an option to bring down the sampling rate would be useful for me, as that's a bit high to risk adding to crucial services.

Thanks! Great tool btw, we were considering building our own internal tool in this vein but this is much nicer.

**Comment by mrowland7** [comment]
* ~1300 goroutines
* 64 CPU cores available
* ~25 CPU cores/second utilized on average

**Comment by petethepig** [comment]
@mrowland7 Thanks for providing the details, this is useful for us!
