### ISSUE TITLE
Disable certain github workflows for forks

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#1538]
E.g in [this PR](https://github.com/pyroscope-io/pyroscope/pull/1537) some of them fail because of permission issues — we should just disable those workflows in those situations.

**Comment by petethepig** [comment]
We should disable these two:
* `.github/workflows/publish-lib-to-npm.yml`
* `.github/workflows/cloud-compability-check.yml`

**Comment by wisdommatt** [comment]
@petethepig I would like to work on this issue

**Comment by petethepig** [comment]
@wisdommatt I think the first one (`.github/workflos/publish-lib-to-npm.yml`) is already done in this PR https://github.com/pyroscope-io/pyroscope/pull/1594/files

**Comment by wisdommatt** [comment]
@petethepig I see, so I think I need to do something similar for .github/workflows/cloud-compability-check.yml.

Maybe I will just go for another issue for now so we don't have conflicts.
