### ISSUE TITLE
any plans to support cpp?

### ISSUE THREAD

**Issue by oak-tree** [pyroscope-io/pyroscope#155]

**Comment by petethepig** [comment]
Hi @oak-tree 

We currently have support for [eBPF profiling](https://pyroscope.io/docs/ebpf) — it allows for cpp profiling, but only work on Linux.

Is there any existing tools you (or others) would recommend for cpp profiling?

**Comment by chadbrewbaker** [comment]
Lots is going on in kernel space that is a bottleneck. It makes sense to do whole system eBPF tracing instead of just a few user space PIDs. For C/C++/Rust it's a matter of getting the debug symbols to the visualization server.

**Comment by abeaumont** [comment]
Apart from eBPF, a specialized C/C++ profiler would also be possible, similar to the [rust profiler](https://github.com/pyroscope-io/pyroscope-rs). A key question here is what the best way to package the C++ agent would be (i.e. there's no Cargo for C++). Suggestions would be welcome here.

**Comment by samuel-emrys** [comment]
> A key question here is what the best way to package the C++ agent would be (i.e. there's no Cargo for C++). Suggestions would be welcome here.

You could do this pretty easily with [Conan](https://docs.conan.io/en/latest/). If you're talking about binary deployment, then you could utilise the [VirtualRunEnv](https://docs.conan.io/en/latest/mastering/virtualenv.html#virtualrunenv-generator) generator to provide access to the package's binary directories in the local cache.

**Comment by yhyu13** [comment]
There is already pretty good ones out there like tracy https://github.com/wolfpld/tracy
