### ISSUE TITLE
Heatmap should show error message if no data is returned

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1551]
![image](https://user-images.githubusercontent.com/23323466/192387894-2272dfe6-d19f-44b1-b4ba-7fa1ee5223b0.png)

Heatmaps should show error message instead of perpetual spinning circle

**Comment by eh-am** [comment]
From what I see sometimes the `heatmap` is `null`.

We can either render as normally and say "there's no data", or fail it completely.

**Comment by Rperry2174** [comment]
I think we should add a message where the heatmap _would_ be and say "No heatmap data for this timerange and application" or something like that and then we should just not render a flamegraph component at all

**Comment by Rperry2174** [comment]
closed in #1565
