### ISSUE TITLE
Duplicated fallback logic at ebpf profiler?

### ISSUE THREAD

**Issue by Jun10ng** [pyroscope-io/pyroscope#1557]
When I'm reading the code of ebpf profiler, i found the following two code logic seem duplicates: if `gosyms == nil`, always falls into `bcc()`.
But I'm not sure about it. 

Gosyms implementation:
https://github.com/pyroscope-io/pyroscope/blob/ae78c42802f56c36d4fee80a9ddd2cd446d541a2/pkg/agent/ebpfspy/symtab/gosym.go#L86-L92

and outside logic:
https://github.com/pyroscope-io/pyroscope/blob/ae78c42802f56c36d4fee80a9ddd2cd446d541a2/pkg/agent/ebpfspy/symbols_linux.go#L61-L64

**Comment by korniltsev** [comment]
They are slightly different.
The first case is to resolve go symbols in go process and fallback to bcc if it can't find go symbol(maybe some shared library, such libc, etc)
And the second case is trying to detect go process(trying to load symbols from gopclntab ) and if it is not go process or it fails for some reason, it will create a bcc implementation

**Comment by Jun10ng** [comment]
> 

Oh Thanks! I forgot the ebpf profiler not only for go process.

By the way, I have another question: where is the `bcc_syms/bcc_syms.h` file? Is it built by `make build-bcc`?

**Comment by korniltsev** [comment]
Yes.
`make build-bcc`
It will clone and build small part of bcc. The header will be `./third_party/bcc/lib/include/bcc_syms/bcc_syms.h`

**Comment by Jun10ng** [comment]
> Yes. `make build-bcc` It will clone and build small part of bcc. The header will be `./third_party/bcc/lib/include/bcc_syms/bcc_syms.h`

Thanks. Which `CFLAGS` command links this header file?  
I only found `libbpf` ralated command at https://github.com/pyroscope-io/pyroscope/blob/cf75b4c7627be7c25a6ccd75fac7673d8c099bff/Dockerfile#L88

**Comment by korniltsev** [comment]
For bcc It is here
https://github.com/pyroscope-io/pyroscope/blob/cf75b4c7627be7c25a6ccd75fac7673d8c099bff/Makefile#L44

The one you linked is for bpf program compilation

**Comment by korniltsev** [comment]
If you have more questions, please open a separate issue/discussion or reach via slack.
