### ISSUE TITLE
Multiple application with same ApplicationName

### ISSUE THREAD

**Issue by jonyhy96** [pyroscope-io/pyroscope#161]
In comparison view, we can only compare under same application. 
When deploy application to k8s, the replicates of pod is always bigger than 1. They shold be treate seperatly but i can't find a way to define it's name appropriately.
How can we deal with situation like this? Will pyroscope support label or something else in config?

**Comment by Rperry2174** [comment]
Thanks for making the issue! As of right now we don't support tags, but we did design the storage engine in a way where they can be added. I created an issue #162.

**Comment by eh-am** [comment]
We now support tags(https://pyroscope.io/docs/flameql/) and comparison view allows comparing 2 arbitrary apps (although UX isn't the best). Closing this.
