### ISSUE TITLE
Issue when comparison / diff timelines are out of range

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1614]
Right now its possible that you could select a time period in the main time range which excludes part of the time range from one of the comparison / diff timeranges below it. 

Most frequently this occurs when the main timeline is set to a "dynamic" range i.e. `now-1h` and then the comparison timelines have a hard-coded value which a few hours from now will no longer be within that time range `now-1h`. 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/23323466/195388547-7e05e205-7f17-431d-a8d1-7796bfecc33c.png">

We should fix this in two parts (definitely the first, maybe the second):
1. We should show a notifcation to alert the user that the baseline or/and the comparison timeline are out of range (can be two separate notifcations if that makes it easier since these are two separate requests i think) 
2. We should makybe give the option inside of the notifcation (i.e. a button) to extend the main timeline to include the comparison/diff timelines

For number 2 it would mean that we "sync" the minimum of the main timeline to be <= the minimum of the main, comparison, and diff timelines and we "sync the maximum of the main timeline to be the maximum of the main, comparison and diff timelines

cc @eh-am

**Comment by eh-am** [comment]
For 1 we could use the existing Notifications code. Although I can see it being quite annoying, so we should have a  "Don't show this again" button within the notification.
