### ISSUE TITLE
configure pyroscope for ruby sinatra application

### ISSUE THREAD

**Issue by vikramcse** [pyroscope-io/pyroscope#1619]
is there any documentation to configure pyroscope for ruby sinatra server, it seems that the documentation only covers for [rails](https://pyroscope.io/docs/ruby/)

**Comment by Rperry2174** [comment]
Hi @vikramcse thanks for reaching out! If you follow the link to our examples folder you can see ruby examples with both rails and [sinatra](https://github.com/pyroscope-io/pyroscope/blob/main/examples/ruby/rideshare/lib/server.rb). Let us know if you have any other questions!

**Comment by Rperry2174** [comment]
going to close let us know if you have any other questions @vikramcse
