### ISSUE TITLE
Sort items in tag explorer tooltip

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#1652]
We could either use sorting settings from the table below or always default to descending order based on number of samples.
![Screen Shot 2022-10-31 at 10 46 51 PM](https://user-images.githubusercontent.com/662636/199167288-c84285e6-d25f-42ef-894e-5c28738789e0.png)

**Comment by Rperry2174** [comment]
Now that I think about it are you sure you want this? As you're moving the tooltip it gets really jumpy if we don't leave the order of the tags constant

**Comment by petethepig** [comment]
Yeah, good point. Let's discuss in person.

**Comment by Rperry2174** [comment]
closing this -- I think we should leave them constant because its easier to read as you move the tooltip around
