### ISSUE TITLE
Merge root nodes of callers in sandwich view

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#1659]
![image](https://user-images.githubusercontent.com/23323466/199266792-fd04ea0f-af89-46d6-bc12-606d47b8aad3.png)

We need to merge the bottom node here, but we need a function to do so and a tree to write that function for

**Comment by petethepig** [comment]
There's a similar issue in callees too
![Screen Shot 2022-11-01 at 8 13 57 AM](https://user-images.githubusercontent.com/662636/199267921-de173476-1ebb-48c1-8ade-c2b4f9b4c7fd.png)

**Comment by Rperry2174** [comment]
also what do the "total" nodes mean at the top of each of the "callers" stacks? should those be removed?

**Comment by petethepig** [comment]
> also what do the "total" nodes mean at the top of each of the "callers" stacks? should those be removed

I'd keep it, I think that one is fine

**Comment by dogfrogfog** [comment]
> also what do the "total" nodes mean at the top of each of the "callers" stacks? should those be removed?

The "total" node is a tree root node. To get stacks im going from root node to target function. Since root node is "total" we see it on top of each stack

**Comment by dogfrogfog** [comment]
> There's a similar issue in callees too ![Screen Shot 2022-11-01 at 8 13 57 AM](https://user-images.githubusercontent.com/662636/199267921-de173476-1ebb-48c1-8ade-c2b4f9b4c7fd.png)

ye...i think we should have ability to merge _same name + same tree level_ nodes..... i think the case with callees and the callers are pretty similar... in both cases we have same [tree](https://github.com/pyroscope-io/pyroscope/blob/main/packages/pyroscope-flamegraph/src/convert/sandwichViewProfiles.ts#L8) and we want to merge nodes with the same paramethers

**Comment by dogfrogfog** [comment]
this is example of `time.Since` tree with unmerged functions + corresponding flamebearer of this tree

**Comment by dogfrogfog** [comment]
here is the example of `rideshare-app-golang.cpu{}` `time.Since` callers [tree](https://pastebin.com/AV6xhZbZ) and [flamebearer](https://pastebin.com/CPsR7CDT).... not exact same as in 1st ss but still pretty close
<img width="1365" alt="Screenshot 2022-11-02 at 13 37 47" src="https://user-images.githubusercontent.com/47758224/199491429-724a3db5-f61f-43a7-93a5-5035a3ca3399.png">

**Comment by dogfrogfog** [comment]
i think the main place to merge is here for [callees](https://github.com/pyroscope-io/pyroscope/blob/main/packages/pyroscope-flamegraph/src/convert/sandwichViewProfiles.ts#L122) and here for [callers](https://github.com/pyroscope-io/pyroscope/blob/main/packages/pyroscope-flamegraph/src/convert/sandwichViewProfiles.ts#L177)

to have smth like this
```
const mergedCalleesTree/mergedCallersTree = merge(totalNode)
// and after we have merged nodes with the same level and name

return { ...result, ...treeToFlamebearer(mergedCalleesTree/mergedCallersTree) }
 
```
