### ISSUE TITLE
Make search functionality more obvious

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#17]
Right now the search bar gets lost in all the colors on the page. Because the typical use case is that someone is using Pyroscope to dig into a particular file / function, we should change the color so that it stands out from the black background

![image](https://user-images.githubusercontent.com/23323466/104784745-cbdfde80-573d-11eb-89c9-9f81d6e0b5b5.png)

**Comment by petethepig** [comment]
I made it white in #21 so closing for now.
