### ISSUE TITLE
Add Grafana Plugin for Pyroscope

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#173]
Many people currently visualize a number of other metrics inside of their Grafana dashboards. We definitely think it would be cool to be able to visualize Pyroscope alongside other tools' data (i.e. Jaeger). We'll likely need to build both a datasource plugin to connect to Pyroscope server and also a panel plugin to visualize the data. You can learn more about those [here](https://grafana.com/docs/grafana/latest/developers/plugins/)
- [Panel Plugin docs](https://grafana.com/tutorials/build-a-panel-plugin/)
- [Data source Plugin docs](https://grafana.com/tutorials/build-a-data-source-plugin/)

We spoke a little with the Grafana team and here are some tips they gave to get us started:
> With tracing they followed this path: https://github.com/grafana/grafana/pull/20297
> 1) adding a datasource to query the Jaeger API for a given trace ID
> 2) Adding a trace result viewer in an iframe that loads the trace from the externally configured jaeger UI
> 3) Add minimal query field with a dropdown to show most recent traces by service
> 4) Integrated a workflow where a log line field showing a trace ID would open that jaeger iframe
> 
> One more tip:
> The Explore API changed slightly since then. To “force” a certain view, you need to set the preferredVisualisationType
> 

https://github.com/grafana/grafana/blob/57f3de74c61d24dbbca266d29836d1a030cff1f4/public/app/plugins/datasource/jaeger/responseTransform.ts#L24

Any input from those who have built grafana plugins before would be greatly appreciated!

**Comment by Slach** [comment]
@petethepig sorry for the question, is this feature implemented or not?
