### ISSUE TITLE
eBPF Profiling only support cpu profiling ？

### ISSUE THREAD

**Issue by sunnoy** [pyroscope-io/pyroscope#1738]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/19342276/202648637-2f3361fc-d3bf-4bfc-bbd0-c48fa952c075.png">

how to  get memory profiling ?

**Comment by petethepig** [comment]
Hi @sunnoy 

Yes, our eBPF profiler can only do CPU profiling right now. To get memory profiles you'd have to use a runtime-specific agent, here's [a list of them](https://pyroscope.io/docs/agent-overview/).

Currently, the only ones that support memory profiling are:
* Go
* Java
* dotnet (support coming out soon)

**Comment by sunnoy** [comment]
ok thks
