### ISSUE TITLE
Tags are not being displayed

### ISSUE THREAD

**Issue by k4kratik** [pyroscope-io/pyroscope#1782]
I was trying latest version 0.35.0 and found a bug.

Basically my tags are not being displayed. (But they will show up If I start typing in the text box).

 `/label-values` request doesn’t occur until I start typing in the text box.

![image](https://user-images.githubusercontent.com/20947380/205035680-9f954e4e-6d64-440d-9584-9d8c34409099.png)

**Comment by Rperry2174** [comment]
should be fixed now thanks for reporting @k4kratik

**Comment by petethepig** [comment]
The fix is in [v0.35.1 release](https://github.com/pyroscope-io/pyroscope/releases/tag/v0.35.1)
