### ISSUE TITLE
Is there any way to get detailed info like Golang's pprof list?

### ISSUE THREAD

**Issue by JobberRT** [pyroscope-io/pyroscope#1833]
Pyroscope is a great tool to help me profile my program. But I found a little bit complex when I can only see the profile result without who causing it(Not function name)

In Go, I can use these cmd to get a detailed info:

`go tool pprof http://localhost/debug/pprof/profile (change the endpoint to profile memory)`
`(pprof) top # Here we can get each function's cpu percentage just like pyroscope`
![image](https://user-images.githubusercontent.com/17498767/216529903-9b8d0549-55e1-46e9-9de9-73b5d83f3ed7.png)

`(pprof) list Function1 # Here we can see excatly how many seconds does each line of code consume.`
![image](https://user-images.githubusercontent.com/17498767/216529989-117032fd-b835-46d9-bbc1-10de153475cd.png)

Is this possiable to achieve in Pyroscope? Both in CPU and MEM?

**Comment by petethepig** [comment]
I think the top image is pretty much our table view. flat = self, cum = total:
![Screenshot 2023-02-03 at 10 41 58 AM](https://user-images.githubusercontent.com/662636/216682038-d60893a5-e482-492e-a97f-ab98bdf90d6a.png)

For the latter pyroscope would need the access to source code. We do not have that functionality right now, so it's not really possible at the moment unfortunately. We have plans for integrating with source code providers like github but this is not implemented yet.

**Comment by JobberRT** [comment]
Thanks for replying,
