### ISSUE TITLE
Consul discovery support in pull mode

### ISSUE THREAD

**Issue by eastfisher** [pyroscope-io/pyroscope#1846]
Hello, I found that pyroscope support static conf and kubernetes discovery in pull mode.

Is there any plan to support [consul discovery](https://developer.hashicorp.com/consul/docs/discovery/dns) natively?

**Comment by Rperry2174** [comment]
no immediate plans -- we're not as familiar with consul so we'll have to take some time to understand how we could make it work

**Comment by eastfisher** [comment]
Pyroscope supports consul service discovery now!
