### ISSUE TITLE
Add support for pull-method of server

### ISSUE THREAD

**Issue by alonlong** [pyroscope-io/pyroscope#187]
the pyroscope' agent supports pushing profile data to server, for the long term, i think it's necessary to consider supporting the pull-method for server, just like the prometheus

**Comment by dannykopping** [comment]
This is a major blocker to my team adopting pyroscope; would love to see this in place

**Comment by Rperry2174** [comment]
Hey @dannykopping thanks for reaching out and good to know. We've actually been discussing this internally (similar issue #204 is on roadmap) and made some progress on it this week. We'll report back as we closer to closing this issue next week!

**Comment by Ehco1996** [comment]
looking forward for this feature

**Comment by Rperry2174** [comment]
This is now added @Ehco1996 @dannykopping @alonlong ! See [examples](https://github.com/pyroscope-io/pyroscope/tree/main/examples/pull) here or documentation [here](https://pyroscope.io/docs/pull-mode)

**Comment by dannykopping** [comment]
Great news @Rperry2174! I'll give this a try as soon as I can :tada:
