### ISSUE TITLE
Make table highlight corresponding items in flamegraph

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#22]
Now that we've added a table we made it so that you can see exactly which functions are consuming resources:
![image](https://user-images.githubusercontent.com/23323466/104853250-6bbf7880-58b4-11eb-92ac-a4cf7f0b3c15.png)

In this case, lets say we wanted to dig into:
`github.com/dgrapah-io/badger/v2.(*levelHandler).numTables`

Right now you could type it into the search bar:
![image](https://user-images.githubusercontent.com/23323466/104853390-5d259100-58b5-11eb-9d7b-cd5339903983.png)

but it would be be better if you could also either hover or click the the item in the table and have the same functionality as the search bar of showing where that item is in the flamegraph

**Comment by LouisInFlow** [comment]
I like clicking, hover might cause animation overload for the user.

Do you imagine more features that would be activated by clicking? Hover-menu? Or should all the functions appear as little icons like the GitHub link

**Comment by Rperry2174** [comment]
Yeah I agree that clicking is better for the table. As far as the Github Icon (this one(#20) I assume); This table functionality definitely seems like a bigger value add so I think we'd rather get the functionality that makes the most sense for clicking on the table and then reevaluate the github Icon / link after.

Either way, I think if both patterns are "click" to make something happen, that's probably the best route here. So right now the functionality for Flamegraph / Table would be:

- Flamegraph hover: shows detail about hovered node
- Flamegraph click:  zooms in on Node and makes node expand 100% 
- Table hover: nothing... 
- Table (cell) click: Highlights node in flamegraph

The only reason I'm hesitant to make Table (cell) click do the same thing as clicking on a node in the flamegraph is because sometimes there can be two nodes that have the exact same name and that seems like an unnecessary issue to deal with (which one to highlight or expand in this case). 

On the other hand, I think if I'm clicking on a cell in the table I just want the node(s) with that name in the Flamegraph to get highlighted somehow so that I can find them and then if I want to see more I'll click one on the flamegraph. 

> How couples are the table and flame graph going to be? If I zoom into function on flame, what happens to table?
For now I think their only relationship would be table -> flamegraph (but no the reverse), however in the future we could potentially go both ways
