### ISSUE TITLE
Update rbspy version to support newer Rubies

### ISSUE THREAD

**Issue by chendo** [pyroscope-io/pyroscope#224]
https://github.com/pyroscope-io/rbspy/ is a tad behind upstream at the moment, with the newest version that pyroscope supports being 2.7.2 whereas upstream is up to 3.0.3: https://github.com/rbspy/rbspy/blob/d81e1dd03be1e8927433a50dd6a41d005fc6e584/src/core/initialize.rs#L495

I had to downgrade to 2.7.2 in our app to evaluate Pyroscope but it looks very handy!

**Comment by petethepig** [comment]
@chendo Good point. We'll update rbspy version in the next release and I think we'll probably try do that on a regular basis going forward.

**Comment by petethepig** [comment]
@kolesnikovae Assigning this to you.

I'm also thinking, could we set up some kind of an automated alert on our jenkins server so that every time there's a new version of phpspy / rbspy / pyspy we get notified in slack?
