### ISSUE TITLE
Create a liveness check endpoint

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#226]
k8s has this feature for services to advertise that they are able to process requests. [Link to documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)

We should implement this for pyroscope. I think we can just add an endpoint somewhere here https://github.com/pyroscope-io/pyroscope/blob/main/pkg/server/controller.go#L63-L66

**Comment by linydquantil** [comment]
This is a good idea
