### ISSUE TITLE
Make pyroscope server expose metrics via prometheus interface

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#229]
List of metrics we want to expose:
* memory stats (gauges)
* disk stats (gauges)
* counter for number of ingestions
* counter for number of renders

TODO: we should do research and see what other metrics do other comparable services expose

**Comment by petethepig** [comment]
I started working on this in https://github.com/pyroscope-io/pyroscope/tree/benchmark-suite branch, but I'm using statsd.

**Comment by eh-am** [comment]
In https://github.com/pyroscope-io/pyroscope/pull/347 we are added a histogram per handler, which also exposes a counter. For example:

```
pyroscope_http_request_duration_seconds_count{code="200",handler="/ingest",method="POST",service=""} 2125
pyroscope_http_request_duration_seconds_count{code="200",handler="/render",method="GET",service=""} 2
```

Apart from that we are also tracking disk stats
```
pyroscope_storage_disk_bytes{name="dicts"} 3.716768e+06
pyroscope_storage_disk_bytes{name="dimensions"} 100381
pyroscope_storage_disk_bytes{name="local_profiles"} 0
pyroscope_storage_disk_bytes{name="main"} 310061
pyroscope_storage_disk_bytes{name="segments"} 1.986986e+06
pyroscope_storage_disk_bytes{name="trees"} 2.811165e+06
```

and memory stats (both manually and metrics exposed via the go client)

**Comment by petethepig** [comment]
Thank you @eh-am for your great work on prometheus metrics and dashboards!
