### ISSUE TITLE
Does pyroscope server support the deployment of multiple machines?

### ISSUE THREAD

**Issue by hiyanxu** [pyroscope-io/pyroscope#234]
Hello:
We have a monitoring system, which is cluster deployment.
We want to make pyroscope-server work in our system, so the pyroscope-server can support the deployment of multiple machines?

**Comment by petethepig** [comment]
@hiyanxu Not right now but we're working on it :)

**Comment by hiyanxu** [comment]
Ok, thank you.

**Comment by Rperry2174** [comment]
hi @hiyanxu for now we support this via Pyroscope cloud, but further progress on this on the open source side can be followed here #169
