### ISSUE TITLE
Notify people when new Pyroscope versions are available

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#253]
Whenever we release a new version we would like to make sure that people are aware of that and are notified to upgrade to the new version. 

We could do this either or both of these ways:
- [ ] In the terminal when Pyroscope server is started / restarted
- [x] On the frontend whenever the version becomes out of date

**Comment by petethepig** [comment]
This is somewhat related to the second one: https://github.com/pyroscope-io/pyroscope/pull/333
