### ISSUE TITLE
OAuth Authentication

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#262]
### Problem

Currently there's no authentication mechanism in pyroscope. Users are asking about it and we need to add something soon.

### Proposed Solution

I'm thinking we could implement OAuth relatively quickly. There's [golang.org/x/oauth2](https://pkg.go.dev/golang.org/x/oauth2) module that provides OAuth functionality.

There's also https://github.com/dghubble/gologin which seems to combine a few of these.

### Services we should add support for now

* [ ] Google
* [ ] GitHub
* [ ] GitLab

### Additional Requirements

We need to make sure that whatever we come up with we can extend with extra functionality later. For example, later down the line we'll probably want to add support for things like:
* basic Auth
* SAML, LDAP
* custom email / password authentication with some local db

**Comment by a-donskoy** [comment]
Would be nice to get some different levels of permissions or option to choose which user or team (for example github one) should have access to which type of data or project. It will cover cases when multiply teams working on different projects which we expose on  a same pyroscope setup

**Comment by dreuse** [comment]
Is there any documentation on this?
