### ISSUE TITLE
Sign In Page

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#263]
We need a sign in page for [authentication feature](https://github.com/pyroscope-io/pyroscope/issues/262). We could use Grafana's page for inspiration.

![Screen Shot 2021-06-24 at 12 29 47 PM](https://user-images.githubusercontent.com/662636/123322591-55fc5200-d4e9-11eb-8317-4bfbcf78ff7a.png)

**Comment by Rperry2174** [comment]
Hey @petethepig is this still in progress? @gogi2811 asked in #273
