### ISSUE TITLE
Cleanup JSX lint errors and warnings

### ISSUE THREAD

**Issue by LouisInFlow** [pyroscope-io/pyroscope#27]
To package.json add

```
    "lint": "eslint ./ --ext .js, .jsx --cache --fix"
```

Fix all the issues

**Comment by gwuah** [comment]
I wanted to pick this up but it seems it's been fixed. guess this issue can be closed now.

**Comment by petethepig** [comment]
@gwuah You're right, I'm closing the issue. There's a similar one for CSS / SCSS linting https://github.com/pyroscope-io/pyroscope/issues/1 if you're interested.
