### ISSUE TITLE
Create UI for Login Page

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#273]
Login page is being created here #262 and we will need a frontend for this. Here's an example from Grafana: 
![image](https://user-images.githubusercontent.com/23323466/124678505-7fb56180-de77-11eb-887b-f4bbefd01c0c.png)

We'll need something along these lines but consistent with style from Pyroscope

**Comment by gogi2811** [comment]
is the UI/UX with respect to Pyroscope Design guidelines ready ?

**Comment by Rperry2174** [comment]
Actually I believe @petethepig made a first attempt at this... Can you post a picture @petethepig ?

**Comment by Rperry2174** [comment]
Ah just realized this is a duplicate of #263 closing and moving discussion to there
