### ISSUE TITLE
Create UI for using Tags

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#281]
We are creating backend for tag support in #280. We also need a frontend that will allow users to drill down past just application name and look into specific tags for an application. 

Over time we will likely expand the _types_ of queries that can be made with tags and possibly even coming up with a (simple) Pyroscope specific query language that matches up with the way we store data in our storage engine. For that reason, we should have _both_ a dropdown, but also an input field that will enable people to eventually type in specific queries (i.e. `tag=hostname.*`) 

This component will likely go beneath the current "application name" dropdown and look something like this:
![image](https://user-images.githubusercontent.com/23323466/125665852-66043c81-00cc-4e4c-8297-f46f5c301edb.png)

Over time we can make this component smarter where it can "autocomplete" based off the available options:
![image](https://user-images.githubusercontent.com/23323466/125665961-a6350b41-bcc2-4f01-896a-7e62dcb6c4f4.png)

Here is a docker-compose to play with example linked above (Grafana + Loki):
https://github.com/jaegertracing/jaeger/tree/master/examples/grafana-integration

**Comment by petethepig** [comment]
@Rperry2174 Can you please send us a docker compose file so that we could play with this Loki + Grafana setup?

**Comment by Rperry2174** [comment]
closed in #296
