### ISSUE TITLE
Make sidebar items actual links so that they can be opened in new tabs

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#305]
This gif illustrates the problem. On github you can right click and open links in new tab, in pyroscope you can't do that.

![2021-07-27 15 20 02](https://user-images.githubusercontent.com/662636/127234967-6b3976a5-3eab-4b1f-9302-05d6ba315d5a.gif)

**Comment by clovis1122** [comment]
I'll take a look!
