### ISSUE TITLE
Custom Date Range Buttons Broke

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#31]
![image](https://user-images.githubusercontent.com/23323466/105132598-0af49380-5aa0-11eb-8b7f-22d943db4630.png)

- [ ] Fix the date range buttons so they work
- [ ] (optional) Write a test to make sure that they don't break again in the future

**Comment by LouisInFlow** [comment]
This is already fixed. It seems that adding "resolve #issue#" is not auto closing issues

**Comment by Rperry2174** [comment]
closed in #36
