### ISSUE TITLE
Add Tooltip for Table 

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#337]
Right now hovering over items in the table doesn't give any useful information, but @olvrng brought up that especially for the diff view a tooltip would be very useful for the table. 

We _might_ be able to separate the tooltip into its own component and somehow share it for the table and the flamegraph. I'm not sure how this will work dealing with the `<canvas>` element for the flamegraph and with the `<table>` element for the tooltip.

Even if we have to make a separate tooltip component for the table, we should definitely have one to give more information.

**Comment by eh-am** [comment]
This should be bit more easy now that we have the tooltip extracted into its own component (https://github.com/pyroscope-io/pyroscope/pull/432)
