### ISSUE TITLE
Serve assets gzipped

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#342]
I think pyroscope should serve assets gzipped

**Comment by gawicks** [comment]
Hi it's @petethepig it's @gawicks from slack. Please assign me to this issue.

**Comment by petethepig** [comment]
Done. Thanks for the help, it's much appreciated!

**Comment by gawicks** [comment]
@petethepig Looks like there's some housekeeping left. Could you link PR #381 to this issue and close 😊

**Comment by petethepig** [comment]
@gawicks Right, I always forget, thanks for the reminder!

**Comment by petethepig** [comment]
Fixed in #381
