### ISSUE TITLE
Handle badgerdb panic

### ISSUE THREAD

**Issue by yasharne** [pyroscope-io/pyroscope#350]
I don't know what to put as the issue title as the exception on the pyroscope is not telling me more information. I got this exception on the `pyroscope server`: 
```
panic: runtime error: slice bounds out of range [:12] with capacity 0

goroutine 1 [running]:
github.com/dgraph-io/badger/v2.(*valuePointer).Decode(...)
	github.com/dgraph-io/badger/v2@v2.2007.2/structs.go:61
github.com/dgraph-io/badger/v2.(*valueLog).populateDiscardStats(0xc0002215d0, 0x7ffffffe, 0x0)
	github.com/dgraph-io/badger/v2@v2.2007.2/value.go:1977 +0x7ec
github.com/dgraph-io/badger/v2.(*valueLog).open(0xc0002215d0, 0xc000221400, 0x240000029e, 0xc034b5f493, 0xc000128390, 0x0, 0xc0005500c3)
	github.com/dgraph-io/badger/v2@v2.2007.2/value.go:1218 +0xe45
github.com/dgraph-io/badger/v2.Open(0xc007872b60, 0x18, 0xc007872b60, 0x18, 0x0, 0x2, 0x2, 0x1, 0x100, 0x17ad220, ...)
	github.com/dgraph-io/badger/v2@v2.2007.2/db.go:396 +0xcf2
github.com/pyroscope-io/pyroscope/pkg/storage.(*Storage).newBadger(0xc0001427e0, 0x147bbff, 0x5, 0xc000221000, 0x0, 0x0)
	github.com/pyroscope-io/pyroscope/pkg/storage/storage.go:80 +0x4a5
github.com/pyroscope-io/pyroscope/pkg/storage.New(0xc0000e88c8, 0x0, 0xc0000a68a0, 0xc000295b40)
	github.com/pyroscope-io/pyroscope/pkg/storage/storage.go:101 +0x1c6
github.com/pyroscope-io/pyroscope/pkg/cli.newServerService(0xc0000c2000, 0xc0000e88c8, 0x4, 0x0, 0x0)
	github.com/pyroscope-io/pyroscope/pkg/cli/server.go:45 +0x105
github.com/pyroscope-io/pyroscope/pkg/cli.startServer(0xc0000e88c8, 0x1, 0x1)
	github.com/pyroscope-io/pyroscope/pkg/cli/server_unix.go:25 +0xc5
github.com/pyroscope-io/pyroscope/pkg/cli.generateRootCmd.func2(0x17acba0, 0xc00002a030, 0xc0000201a0, 0x1, 0x1, 0xc00009b740, 0x0)
	github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:117 +0x32
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc000151760, 0x17acba0, 0xc00002a030, 0x0, 0x0)
	github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:153 +0x1b2
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc000151b80, 0x17acba0, 0xc00002a030, 0x0, 0x0)
	github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:157 +0x125
github.com/peterbourgon/ff/v3/ffcli.(*Command).ParseAndRun(0xc000151b80, 0x17acba0, 0xc00002a030, 0xc000020190, 0x2, 0x2, 0x1, 0xc0000e8840)
	github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:169 +0x7e
github.com/pyroscope-io/pyroscope/pkg/cli.Start(0xc0000e8840, 0xc0000e8840, 0x16fd000)
	github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:208 +0x98
main.main()
	github.com/pyroscope-io/pyroscope/cmd/pyroscope/main.go:11 +0x3f
```
deleting the pyroscope pod didn't solve the problem, only deleting the PVC fixed it. Here is my configuration file:
```
    # disables analytics
    analytics-opt-out: "yes"

    # log level: debug|info|warn|error
    log-level: "info"

    # log level: debug|info|warn|error
    badger-log-level: "error"

    # directory where pyroscope stores profiling data
    storage-path: "/var/lib/pyroscope"

    # port for the HTTP server used for data ingestion and web UI
    api-bind-addr: ":4040"

    # base URL for when the server is behind a reverse proxy with a different path
    base-url: ""

    # Percentage of memory at which cache evictions start.
    cache-evict-threshold: "0.25"

    # Percentage of cache that is evicted per eviction run.
    cache-evict-volume: "0.33"

    # Indicates whether value log files should be truncated to delete corrupt data, if any.
    badger-no-truncate: "false"

    # Disables /debug/pprof route.
    disable-pprof-endpoint: "false"

    # max number of elements in LRU cache for dimensions
    cache-dimension-size: "1000"

    # max number of elements in LRU cache for dictionaries
    cache-dictionary-size: "1000"

    # max number of elements in LRU cache for segments
    cache-segment-size: "1000"

    # max number of elements in LRU cache for trees
    cache-tree-size: "10000"

    # max number of nodes used when saving profiles to disk
    max-nodes-serialization: "2048"

    # max number of nodes used to display data on the frontend
    max-nodes-render: "2048"

    # Threshold value to consider out of space in bytes.
    out-of-space-threshold: "512.00 MB"

    retention: "5d"  
```
I was using version `0.0.34` and upgrading it to version `0.0.37` didn't fix it as well

**Comment by kolesnikovae** [comment]
@yasharne Thank you for filing the issue. If you run pyroscope server in Kubernetes with persistence, please make sure pod security context `fsGroup` is set to `101` so that [it matches user ID](https://github.com/pyroscope-io/helm-chart/tree/main/chart/pyroscope#persistence) in the official docker image.

I think that this failure should be handled properly on the pyroscope server end. And it also may make sense to set `fsGroup` by default.

**Comment by yasharne** [comment]
Thanks @kolesnikovae for your response, Actually we are using openshift and duo to our `scc`  we are not allowed to set 101 as `fsGroup`
are there any other ways to handle this?

**Comment by kolesnikovae** [comment]
> Thanks @kolesnikovae for your response, Actually we are using openshift and duo to our `scc` we are not allowed to set 101 as `fsGroup`
> are there any other ways to handle this?

Unfortunately, I'm unaware of alternative ways. But I can that this is the recommended method (
https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/#allow-users-to-skip-recursive-permission-changes-on-mount):
> Traditionally if your pod is running as a non-root user (which you should), you must specify a `fsGroup` inside the pod’s security context so that the volume can be readable and writable by the Pod. This requirement is covered in more detail in here.

Cluster administrators should be able to set up a proper scc.

**Comment by yasharne** [comment]
@kolesnikovae Sorry I didn't explain it clearly, I ment we can set `fsGroup` but the number cannot be `101`, the allowed number range is different, starting with something like `1024000`

**Comment by kolesnikovae** [comment]
Oh, I see, that makes sense. Thank you for clarification :) My first answer (and our docs re this issue) is a bit confusing. The exact value of `fsGroup` does not really matter much – you can set it to a value from the allowed range, e.g:
```
podSecurityContext:
  fsGroup: 1024001
```

This includes all processes of the container to the supplemental group 1024001 and makes kubelet to change the ownership of mounted volumes to this group (recursively; setgid bit is set).

Depending on the SCC applied you may also need to specify `runAsUser`.
