### ISSUE TITLE
Optimize bundle size

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#355]
If you run webpack in watch mode and open localhost:8888 you can see the breakdown between different libraries. It looks like this right now:

![Screen_Shot_2021-08-26_at_3_37_57_PM](https://user-images.githubusercontent.com/662636/131045101-5f67e9e9-f8d2-4510-9c2c-fee0fe9a9dcf.png)

I think a lot of these would be easy to fix by just adjusting the way we import things, e.g here's an issue in fontawesome repo: https://github.com/FortAwesome/react-fontawesome/issues/70

**Comment by Rperry2174** [comment]
closed in #362
