### ISSUE TITLE
Add Documentation for Authentication Flow

### ISSUE THREAD

**Issue by tuananh2508** [pyroscope-io/pyroscope#367]
#Issue 
We currently run Pyroscope in our K8s Cluster (installed by Helm) and using NodePort sevice type for it. But till now, I didn't see there is any option to secure the Pyroscope server ? Cause obviously we dont want some stranger can access the Service. 
Thanks

**Comment by Rperry2174** [comment]
Glad to see that you're running Pyroscope! We actually added support for authentication in #272 which is included in the most recent release for Pyroscope. 

The last step is that we need to document this feature so we will do that and then report back here.

**Comment by tuananh2508** [comment]
Thanks! Glad to hear. We looking forward for it !

**Comment by Rperry2174** [comment]
Thanks for closing @tuananh2508 we're planning on adding a little bit more here about some edge cases so let us know if you run into any issues. 

In the meantime, looks like you found the documentaiton: 
https://pyroscope.io/docs/auth-google

**Comment by dreuse** [comment]
Hi @Rperry2174 is this feature only available to the enterprise version? I couldn't find how to achieve this in the OSS.
