### ISSUE TITLE
Pyroscope exec args parsing error in 0.0.38

### ISSUE THREAD

**Issue by xqzhou** [pyroscope-io/pyroscope#368]
#### Cmd to reproduce
```
pyroscope exec python3 -m http.server 8000
```

#### Error
```
Error: unknown shorthand flag: 'm' in -m
```

Previous version working fine

**Comment by kolesnikovae** [comment]
Thank you for reporting the issue @xqzhou. I confirm the problem, working on the fix.

As a temporary workaround you can separate pyroscope args and the command by `--`, i.e.:
```shell
pyroscope exec -- python3 -m http.server 8000
```
