### ISSUE TITLE
Add Document on Data Retention feature

### ISSUE THREAD

**Issue by tuananh2508** [pyroscope-io/pyroscope#399]
# Issue
I see that Pyroscope now have the feature that allow user to setup data retention on #182.
But I can't find any Document on [pyroscope.io](url) for it ?

**Comment by petethepig** [comment]
@tuananh2508 Thanks for reporting this, we'll add something to the docs soon!

In the meantime, you can use `pyroscope server --help` and search for `--retention` argument:
```
  --retention                0s
    sets the maximum amount of time the profiling data is stored for. Data before this threshold is deleted. Disabled by default

```

The way it works right now is you can set retention period in seconds and pyroscope server will automatically delete data create before the threshold you provide via `--retention` argument.

**Comment by tuananh2508** [comment]
Thanks for the answer. 
But we installed Pyroscope with Helm chart and I can't find the option for it in Helm Chart. 
After read your answer I tried to exec the command in the Pod but It's doesn't work because the main process is using the Badger database already.
For now, We still use very large PVC for it ( ~500GB), but still I think if there is an option for retention in `values.yaml` would be great in a long run. 
For quick fix, can I do manual do the cleanup by deleting the data in `/var/lib/pyroscope/` ?

**Comment by kolesnikovae** [comment]
@tuananh2508, thank you for reporting the issue! Indeed, the helm chart documentation can confuse. Actually, you can specify `retention` parameter in `values.yaml`: 

```yaml
pyroscopeConfigs:
  retention: 720h # 30 days
```

I've prepared a PR (https://github.com/pyroscope-io/helm-chart/pull/15) – hope it will make configuring more transparent. I'd be more than happy to get feedback on this: I feel that at this point the documentation requires improvements.

Regarding the quick fix: unfortunately, manual partial removal is not possible – you can only drop all the data. Also, I'd suggest you to take a backup before upgrade :)

**Comment by Rperry2174** [comment]
Added here https://pyroscope.io/docs/data-retention/
