### ISSUE TITLE
Add context menu to flamegraph canvas 

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#441]
When inspecting a flamegraph and you click on a node that node becomes highlighted and the nodes above it become dimmed. Sometimes you only care about the node towards the bottom of a stacktrace, but you're stuck with a bunch of dimmed nodes that you don't care about (at the time) above it. 

![image](https://user-images.githubusercontent.com/23323466/136308050-ddcbe8c1-56e2-4310-9ff5-83d87277ba5c.png)

We should add "collapse" arrow functionality similar to code editors that allows you to collapse the nodes you don't care about similar to this video:
![collapse_button_vid_02](https://user-images.githubusercontent.com/23323466/136308013-54a2ac69-6278-43fe-bb57-cdb4bab68408.gif)

Might be worth doing alongside #24 as a more general "improve canvas experience" project

**Comment by Rperry2174** [comment]
From Slack another way of doing this would be adding right click functionality where users can right click and select to either "focus" on a node or to "collapse" the nodes above it via a dropdown menu. 

For now the two most simple options could be:
- Focus: Which would dim the nodes above
- Collapse: Which would collapse the nodes above
(or something along these lines)

![Peek 2021-10-07 14-03](https://user-images.githubusercontent.com/23323466/136632690-b26dc08c-e745-42a0-aff5-6eecfc6751d0.gif)

The benefit from this is that it would also allow for us add more functionality here in the future. For example, opening the source code on Github as mentioned in #454.

**Comment by eh-am** [comment]
Implemented in #480
