### ISSUE TITLE
Add Tags support for Grafana 

### ISSUE THREAD

**Issue by tuananh2508** [pyroscope-io/pyroscope#449]
From Pyroscope 0.0.39, `tags` feature is available. But on Grafana Dashboard, user still only can choose application name (without tag) to view. This would cause some problem for user who run multiple application with the same pyroscope's application name.

**Comment by eh-am** [comment]
Feature available in version v1.1.0 :confetti_ball:  https://github.com/pyroscope-io/grafana-datasource-plugin/releases/tag/v1.1.0
