### ISSUE TITLE
PDF export is broken

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#451]
These buttons don't work right now

<img width="242" alt="Screen Shot 2021-10-07 at 9 56 58 PM" src="https://user-images.githubusercontent.com/662636/136500748-1c6f10ec-8d0d-4da2-8219-5afd78c9fd7c.png">

@Rperry2174 do we really need pdf export? the library for pdf export is pretty huge. Maybe we could export in csv or something like that? Or pprof?

**Comment by Rperry2174** [comment]
I wouldn't be opposed to getting rid of the pdf option. I think exporting to other formats would be much more useful when we get around to it (I.e html or pprof)

**Comment by eh-am** [comment]
As per https://github.com/pyroscope-io/pyroscope/pull/493 we removed PDF export
