### ISSUE TITLE
Show a message when there's no data available

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#483]
We used to have this
![image](https://user-images.githubusercontent.com/6951209/139462729-520efec2-71b6-4d65-84e4-d8dec5114781.png)

But in one of the refactors it got (accidentally) removed:
![image](https://user-images.githubusercontent.com/6951209/139462622-5925e3c5-7148-4b1a-ba1f-0d90728afb28.png)

It would be nice to have it back, with tests and whatnot.

**Comment by clovis1122** [comment]
I'll take a look at this one!

**Comment by Rperry2174** [comment]
Awesome thanks @clovis1122 let us know if you have any questions
