### ISSUE TITLE
Java Agent - PYROSCOPE_PROFILER_EVENT always itimer

### ISSUE THREAD

**Issue by netamego** [pyroscope-io/pyroscope#485]
Hi,

Hello I refer here this bug:

https://github.com/pyroscope-io/pyroscope-java/issues/1

Thanks a lot.

**Comment by Rperry2174** [comment]
Thanks for reporting this bug / referring to this repo! i will add it to the roadmap and we'll look into it more

**Comment by Rperry2174** [comment]
Hey @netamego should be working now! Let us know if you have any issues or other feedback
