### ISSUE TITLE
New version in the footer mismatch with actual latest version

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#494]
Feature originally developed in https://github.com/pyroscope-io/pyroscope/pull/333

Here's an example posted in slack:

The user is running 0.2.4 but the message says 0.2.3 is the latest version!
![image (27)](https://user-images.githubusercontent.com/6951209/139847662-e5c984a5-5a00-4e7b-a4de-aceceee3c26d.png)

**Comment by petethepig** [comment]
This might be because of the resent split of the docs repo. I'll investigate

**Comment by Rperry2174** [comment]
![image](https://user-images.githubusercontent.com/23323466/146446492-07511511-7a39-44fa-b820-9ea1aa0d7aee.png)

Still seeing this issue /cc @petethepig

**Comment by petethepig** [comment]
I think it's a race condition where the demo gets deployed on the new version before we even update the latest-version.json on pyroscope.io

I'll figure something out..

**Comment by eh-am** [comment]
After talking with @petethepig 
It looks like we need to parse semVer and check if the current version is smaller than the "newer" version.

https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/Footer.tsx#L35
