### ISSUE TITLE
Clicking on item on the table should populate the highlight

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#500]
This idea was previously discussed in slack

Clicking on a table item
![image](https://user-images.githubusercontent.com/6951209/140332407-9f8f9169-7341-4c75-9649-847f23ca7cd4.png)

Should populate the highlight search
![image](https://user-images.githubusercontent.com/6951209/140332471-d5925fbc-2d06-4f3c-90fe-b02e76ca20ef.png)

**Comment by gabrielzezze** [comment]
Hello @eh-am,

This seems pretty straightforward, would have no problems working on this if that's ok!

Thanks.

**Comment by eh-am** [comment]
hey Gabriel, it's all yours! 
 let me know if you have any issues
