### ISSUE TITLE
Better handling of requests

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#506]
- [ ] Retries
- [ ] Message when request fail

For example, here the request failed but spinner continues indefinitely, without any information to the user:
![Peek 2021-11-05 11-53](https://user-images.githubusercontent.com/6951209/140530631-0e4e319d-4bd4-4cfb-9978-316fc97f0a8f.gif)

**Comment by petethepig** [comment]
Retries might be an overkill, but we definitely need some message to show to users.

**Comment by Rperry2174** [comment]
What about just a timeout with a message. I feel like when I end up in this state a simple refresh fixes it

**Comment by eh-am** [comment]
Closing in favor of https://github.com/pyroscope-io/pyroscope/issues/622
