### ISSUE TITLE
Export flamegraph as SVG

### ISSUE THREAD

**Issue by waywardmonkeys** [pyroscope-io/pyroscope#525]
It would be nice to export the current flamegraph view as SVG, including tooltips.

I'd like to be able to grab a sample of data and share it with others.

**Comment by eh-am** [comment]
Hey @waywardmonkeys, this is something we've been discussing internally. I would love to hear your thoughts on exporting as HTML instead of SVG! (Which is something we are more inclined to for other reasons)

**Comment by waywardmonkeys** [comment]
HTML is fine too! Perhaps even better! I just want to be able to share something interactive that is a single file.
