### ISSUE TITLE
Alert user with text if startDate > endDate

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#54]
We have a new DatePicker dropdown, but now its easier to accidentally choose an `endDate` that is smaller than `startDate`. When `state.startDate > state.endDate` then we should add some red text to the bottom to alert the user that they have an invalid date range. 

This way they will not accidentally wait for the data to update for an invalid date range.

<img width="1680" alt="Screen Shot 2021-01-30 at 4 54 22 PM" src="https://user-images.githubusercontent.com/23323466/106372406-22474280-6324-11eb-904d-85b7c5b4797c.png">

**Comment by abaali** [comment]
i can fix this.

**Comment by petethepig** [comment]
This is an example from grafana 
![image](https://user-images.githubusercontent.com/662636/106403930-baf1c700-63e5-11eb-845c-b6572b750529.png)
