### ISSUE TITLE
Create a blessed dropdown component

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#548]
Currently we have 2 kinds of dropdowns: the native one (`<select>`) and `szhsin/react-menu`, for sake of consistency let's only use react-menu, since it's has more features.

First step is to create a DropdownComponent in the `webapp/javascript/ui` directory and a story (from storybook, directory `stories`) showing how to use it.

**Comment by ruslanpascoal2** [comment]
I would like to tackle this issue 🙂

**Comment by eh-am** [comment]
Closed in favor of https://github.com/pyroscope-io/pyroscope/issues/618
