### ISSUE TITLE
DateRange breaks page if dates are updated in the wrong order

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#55]
Bug introduced in #53 

Steps to reproduce:
- Open the page
- Select a new date from the second `DateRange` component

![image](https://user-images.githubusercontent.com/23323466/106396900-9e429880-63bf-11eb-9ad8-f4416622b347.png)

It's worth noting that this happens when you change the second `DateRange` component _before_ you change the first one. 

/cc @abaali

**Comment by abaali** [comment]
this happens because the value of from is still a string ('now-1h') which makes moment.js return a non-valid date 
I'm working on this.

**Comment by petethepig** [comment]
I think the best way of fixing it would be to copy the time parsing logic from the backend to frontend:

* this is where it is on the go side: https://github.com/pyroscope-io/pyroscope/blob/master/pkg/util/attime/attime.go#L18
* that one is based on the original logic in graphite project: https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/attime.py#L30

and so if we had an `attime` parser on the frontend we could parse these `now-1h` strings and turn them into time

**Comment by abaali** [comment]
good suggestion @petethepig  but I already worked on a different one but it needs some improvements.
check it in my new [PR](https://github.com/pyroscope-io/pyroscope/pull/56)

**Comment by Rperry2174** [comment]
closed in #56
