### ISSUE TITLE
Align "Select left/right time range" to the side

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#552]
Currently they are weirdly aligned:
![image](https://user-images.githubusercontent.com/6951209/142639065-edc3ff2d-2d4f-4429-ba75-d3fffbb55b45.png)

We want something like this
![image (29)](https://user-images.githubusercontent.com/6951209/142639409-ad778f11-00f6-4c03-80ad-268c8adbd11c.png)

Also double check they have the same size.

**Comment by Rperry2174** [comment]
closing from #565 thanks @ruslanpascoal2 !!!
