### ISSUE TITLE
Persist frontend data

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#591]
Currently there's no frontend persistence, which means every time one refreshes the page, configurations like Fit Mode, Table/Flamegraph/View etc have to be set again, which makes the experience annoying.

There's been some internal discussions about using [notifications](https://github.com/pyroscope-io/pyroscope/pull/586) to inform about new versions. In that case, after dismissing the notification for a specific version, that notification should never show up again. Which requires again, some kind of frontend persistence.

The idea is to store that data in the redux store and then persist/retrieve to/from localstorage.

Other potentially persistable items:
- [x] Sidebar collapsed state
- [x] Selected application (or application that loads when you load the dashboard)

![Peek 2021-12-08 10-34](https://user-images.githubusercontent.com/6951209/145217237-74e10f75-f1f1-4833-8dc9-07967f2eb9b8.gif)

**Comment by Rperry2174** [comment]
Should we merge this with #587 @eh-am

**Comment by eh-am** [comment]
We can use https://github.com/rt2zz/redux-persist
