### ISSUE TITLE
Add API for adding Annotations on the timeline

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#594]
We should add ability for users to add annotations via an API.

For example, this is what those look like in grafana:

![Screen Shot 2021-12-08 at 5 37 17 PM](https://user-images.githubusercontent.com/662636/145318518-bc5448bc-0c86-4a5c-95e3-ceaedcc1e149.png)

* [ ] We could start by having a simple API for creating these:

```
# this api is copied from graphite:
#  https://www.hostedgraphite.com/docs/api/annotations-and-events.html#creating-an-annotation-for-the-impatient

curl -X POST http://pyroscope:4040/api/v1/annotations -d "title=new deploy"
```

* [ ] then we could add something on the frontend to render these

**Comment by Rperry2174** [comment]
@petethepig should we merge this with #97 ?

**Comment by petethepig** [comment]
@Rperry2174 oops, my bad. we could have both I guess, yours could be the next step where a user can add their own annotations, and it can use the same api we implement in this issue.

**Comment by Rperry2174** [comment]
hey @petethepig until we get support for sql or something along those lines, should we just store this kind of information in badger?

**Comment by petethepig** [comment]
@Rperry2174 oh yeah, definitely

**Comment by Rperry2174** [comment]
Adding some similar apis for reference:
- https://docs.honeycomb.io/api/markers/
- https://github.com/honeycombio/honeymarker
- https://grafana.com/docs/grafana/v9.0/developers/http_api/annotations/
