### ISSUE TITLE
Rewrite Rideshare Example in Golang

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#605]
We currently have a rideshare example for [ruby](https://github.com/pyroscope-io/pyroscope/tree/main/examples/ruby) and [python](https://github.com/pyroscope-io/pyroscope/tree/main/examples/python). 

These examples are great for helping people understand how to use multiple key features from Pyroscope (particularly Tags and diff view) 

We added support for [tags in Go](https://pyroscope.io/docs/golang/#tags) as well, but currently don't have a good example that shows using them and so it would be great to rewrite this example using Go as the language and add it to the examples folder for golang. 

Reusable parts:
- `Dockerfile.load-generator` and [load-generator.py](https://github.com/pyroscope-io/pyroscope/blob/main/examples/python/flask/load-generator.py): will create load and send it randomly to three hosts and three endpoints
- [docker-compose.yml](https://github.com/pyroscope-io/pyroscope/blob/main/examples/python/flask/docker-compose.yml): will create three regions with otherwise identical code

Key parts that need to be rewritten in go:
- server: Will set up routes for `/bike` , `/car` and `/scooter` which will handle traffic for each respective endpoint
- find_nearest_vehicle(search_radius, bike): a [function which lives in a utility file](https://github.com/pyroscope-io/pyroscope/blob/f37370680047055f6d6be97eeb611873a9b44581/examples/python/flask/lib/utility/utility.py#L28-L35) which will take the inputs, and **add an appropriate tag** based on those endpoints, and then complete some arbitrary work ( a while loop )

Note: we created separate folders for bike, car, scooter, and utility because it helps with more meaningful coloring in the resulting flamegraph at the end.

**Comment by deepto98** [comment]
@Rperry2174 Can I pick this up? Although I'm new to Golang, but would like to give this a try.

**Comment by Rperry2174** [comment]
ahh sorry @deepto98 forgot to close this issue in #634 .. Let me see if there's another good starting issue though!

**Comment by Rperry2174** [comment]
Hey @deepto98 thought some more about this and while we do currently have this example for golang in push mode, we also have a pull mode examples folder for golang and currently this example doesn't exist there... Might be worth taking a look at if you're interested! 

https://github.com/pyroscope-io/pyroscope/issues/733
