### ISSUE TITLE
Add UI/UX Improvements to Tag Dropdown

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#618]
Related to #548

Currently the "tag" dropdown has no kind of limit on how many tag values can be shown for any particular key. Although we don't recommend people to use high cardinality fields (i.e. `user_id` in this example) sometimes this will happen. 

Either way we should add some additional functionality to this dropdown to be able to prevent a case where the dropdown is 100+ items long and runs down the entire vertical length of the page:

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/23323466/146440804-a75053d0-5191-41eb-b117-a6835a6cb449.gif)

Some ideas to clean this up:
1. When a "key" is selected, in this case, `user_id` the resulting values should have their top aligned with the key itself (instead of currently when you click `user_id` the values that show up go far off the page both above and below... 
2. We should also add a search bar so that users don't have to scroll around and look for a particular value underneath that key

![image](https://user-images.githubusercontent.com/23323466/146442691-2256bfc5-3f02-4f10-a8b5-e08ebb9b8ee6.png)

Something like this -- styled better of course -- would do nicely there ([codepen](https://codepen.io/robstinson/pen/jOqvwBW)): 
![image](https://user-images.githubusercontent.com/23323466/146443008-d741e04a-cee1-46ed-a619-93e53e189bfe.png)

The above two items are highest priority for this issue. This next one would be a _nice to have_ but I don't know if we necessarily need this _yet_
3. If we could find some way to only show i.e. 20 tag values and then have a pagination button that allows you to see the next 20 etc that would also greatly improve performance when the page has a ton of tag values 

something like this (note the pagination part at the bottom most importantly):
![image](https://user-images.githubusercontent.com/23323466/146443750-aa1e46ff-cd42-4e43-a1c9-794537ad54ff.png)

**Comment by eh-am** [comment]
We are using `szhsin/react-menu` which supports both operations (searching and adding a scrollbar):

* https://szhsin.github.io/react-menu/#focusable-item
* https://szhsin.github.io/react-menu/#menu-overflow
