### ISSUE TITLE
Improve timeline UI when showing a single bar

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#621]
### The Bug
Currently when "zooming" in on the timeline to view single bar, what the timeline eventually shows is an empty timeline with a bar at the far left and a bar at the far right:
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/23323466/146468069-4439d402-ce26-485c-a872-9abebc015f86.gif)

![image](https://user-images.githubusercontent.com/23323466/146468165-a87aae97-36de-477d-89bc-73b08c6f87ca.png)

![image](https://user-images.githubusercontent.com/23323466/146469147-d1932f83-6c32-4bc7-94f5-2c65e1085e46.png)

### Fixing the bug
Instead we should update the timeline so that when it is rendering a single unit of time aka 1 yellow bar, that that bar shows up in the center of the timeline instead of showing a bar on the left and a bar on the right.

**Comment by eh-am** [comment]
Suffice to say, it's a good idea to add tests to cover existing functionality and (re)writing it in typescript.

**Comment by shaleynikov** [comment]
This behaviour is implemented by flot itself and it's spread across few locations in the code.

So the way I want it to implement would be:
1. Detect that we have only 1 chunk of data under selection
2. Change graph settings allowing to display only 1 chunk of data in the very center

This may require to prohibit zooming in when there is no data chunks selected to avoid empty view
