### ISSUE TITLE
Changing main timeline in Comparison view should change the flamegraphs

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#638]
This probably was introduced when we moved the data to the redux store.

Basically when the main timeline changes, the flamegraphs should change as well, since the left/right timelines were affected.
![Peek 2021-12-21 11-45](https://user-images.githubusercontent.com/6951209/146948904-e064edc6-b122-4b87-85ff-cf4e8e55cf27.gif)

**Comment by Rperry2174** [comment]
Yeah also similar: #351 

We should maybe make it so that:
- the minimum of the left time range is also the minimum of the main time range
- the maximum of the right time range is the max of the right time range

**Comment by abeaumont** [comment]
The Diff View also seems broken, in a similar way.

**Comment by eh-am** [comment]
Actually the left/right timelines aren't really affected, so this works as intended.
