### ISSUE TITLE
Replace prelude-ts for ts-belt

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#644]
When refactoring the flamegraph we added [prelude-ts](https://github.com/emmanueltouzery/prelude-ts) for Optionals usage. Turns out it doesn't tree shake very well, making our bundle bigger than necessary

[ts-belt](https://mobily.github.io/ts-belt/api/option) on the other hand is tree shakeable and supports the 2 data structures we are interested in, `Option`and `Result`

Also may be a good idea to just expose those 2 under a `@utils/fp` or something.

**Comment by eh-am** [comment]
Their use of Opaque Types makes certain things a bit more difficult than we expect: https://github.com/mobily/ts-belt/issues/11

**Comment by mobily** [comment]
hello @eh-am 👋 ts-belt author here, I'm looking into it! in the meantime, could you provide more details on why opaque type (Option) causes a problem in your implementation?

**Comment by mobily** [comment]
@eh-am the `Option` type in `ts-belt@3.8.0` is now `type Option<T> = T | undefined | null`, I hope this will help finishing your implementation using `ts-belt`! 🚀

**Comment by eh-am** [comment]
Hey @mobily! That's actually good to know, but we ended up going with `true-myth`, which has a closer API to what we were using and it's been here for longer.
