### ISSUE TITLE
Grafana Panel: fix PNG export

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#648]
https://user-images.githubusercontent.com/6951209/147241065-f5ef20c3-f414-4357-833c-72247e0ebed6.mp4

If not possible, I think just not allowing to exporting anything in grafana should be an ok solution.

**Comment by Rperry2174** [comment]
So we have access to the Pyroscope url from this panel? 

For example if someone is connecting to their Pyroscope instance at localhost:4040?

If so then another solution could be a link that says "go to Pyroscope dashboard" which would then open localhost:4040 so they can get the functionality that isn't available in the dashboard.

**Comment by eh-am** [comment]
>Do we have access to the Pyroscope url from this panel?
I need to investigate more, so far I would say no, since datasource and panel are different plugins. But there may be a way.


>If so then another solution could be a link that says "go to Pyroscope dashboard" which would then open localhost:4040 so they can get the functionality that isn't available in the dashboard.

Not necessarily we will have access to that, for example if datasource access is configured via the server (see pic attached), we can't assume the Pyroscope UI will be available, since it could be a "headless" setup where for example there's a proxy that only authorizes requests coming from the grafana server.

![image](https://user-images.githubusercontent.com/6951209/147256405-f62c2384-acf5-4e60-95ce-44140e0602db.png)

**Comment by eh-am** [comment]
Decided that for now we simply won't allow exporting anything in grafana https://github.com/pyroscope-io/pyroscope/pull/620/commits/656bd793d476755b214336ad0992e3caee38400d
