### ISSUE TITLE
Add authentication methods for API access

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#655]
Now that we have OAuth support for viewing the data we need to add authentication support for API clients, particularly:
* client integrations
* grafana datasource

Currently, when set up with OAuth client integrations bypass authentication altogether (`/ingest` doesn't do authentication), and grafana panel can't access data at all. We need some way of setting some API keys for both.

**Comment by eh-am** [comment]
For grafana datasource we need to do the following

add the input to support API_KEY  https://github.com/pyroscope-io/pyroscope/blob/main/grafana-plugin/datasource/src/ConfigEditor.tsx#L27-L39

2. update the fetch calls to use that API_KEY as header https://github.com/pyroscope-io/pyroscope/blob/main/grafana-plugin/datasource/src/ConfigEditor.tsx#L27-L39

**Comment by kolesnikovae** [comment]
* Documentation: https://github.com/pyroscope-io/docs/pull/43
* Rust: https://github.com/pyroscope-io/pyroscope-rs/issues/16.
* Grafana datasource plugin: https://github.com/pyroscope-io/pyroscope/pull/844
* Go, Python, Ruby, Java, `exec`, `connect`, `agent` already support this.

**Comment by petethepig** [comment]
Released in 0.10.2
