### ISSUE TITLE
chore: Lint TypeScript / JavaScript code

### ISSUE THREAD

**Issue by abeaumont** [pyroscope-io/pyroscope#666]
(I'm following the same approach successfully used for Go linting in https://github.com/pyroscope-io/pyroscope/issues/49,  copy and pasting unashamedly :smile: )

### Community Call To Action

Feel free to open PRs, even if it's one or two small fixes. This kind of work is important but often overlooked. This is a great way to learn more about the internals of the project and we'd appreciate any help on this.

### Summary

We use [eslint](https://github.com/eslint/eslint) as the main linter.

### How to tackle these

Run the linter. It will print a bunch of issues in the code
```
yarn lint
```
Sample output:
```
[...]
/path/to/pyroscope/webapp/javascript/ui/Sidebar.tsx
2:8   warning  'React' was used before it was defined                                                         no-use-before-define
28:25  warning  Function name `Sidebar` must match one of the following formats: camelCase                     @typescript-eslint/naming-convention
41:17  warning  Function name `MenuItem` must match one of the following formats: camelCase                    @typescript-eslint/naming-convention
51:17  warning  Function name `SubMenu` must match one of the following formats: camelCase                     @typescript-eslint/naming-convention
81:14  warning  Variable name `Menu` must match one of the following formats: camelCase, UPPER_CASE            @typescript-eslint/naming-convention
82:14  warning  Variable name `SidebarHeader` must match one of the following formats: camelCase, UPPER_CASE   @typescript-eslint/naming-convention
83:14  warning  Variable name `SidebarFooter` must match one of the following formats: camelCase, UPPER_CASE   @typescript-eslint/naming-convention
84:14  warning  Variable name `SidebarContent` must match one of the following formats: camelCase, UPPER_CASE  @typescript-eslint/naming-convention

✖ 589 problems (0 errors, 589 warnings)

Done in 15.48s.
```

Pick any of these and try to fix it. Some of them are trivial, and some require a deeper understanding of the underlying code. If you have any questions, or if something doesn't work, reach out to me on [our slack](https://pyroscope.io/slack) or open issues.

### Progress

At the time of writing (Jan 3rd) we're at `589 problems (0 errors, 589 warnings)`

**Comment by abeaumont** [comment]
cc: @eh-am in case you have any insight to add about how to solve the issues (feel free to edit the description).

**Comment by eh-am** [comment]
I think we can loosen this rules a bit, like that `@typescript-eslint/naming-convention` example.

One thing that's very important here is to add `strict: true` to our `tsconfig.json` (https://www.typescriptlang.org/tsconfig#strict), that will require us to handle many cases where we've been a bit...careless.

**Comment by abeaumont** [comment]
> I think we can loosen this rules a bit, like that @typescript-eslint/naming-convention example.

We can disable the rule where it makes sense, I'd consider that part of the clean-up work. It's different if we want to remove rules completely because they aren't helpful, it'd be nice to remove those at the very beginning if there are any.

**Comment by eh-am** [comment]
We have those in https://github.com/pyroscope-io/pyroscope/blob/b46e7b8ee4a2fc4acf0bea9bd13146db56ef96fe/.github/workflows/tests-js.yml#L48 now
