### ISSUE TITLE
Tag selection doesn't use `base-url` value

### ISSUE THREAD

**Issue by dannykopping** [pyroscope-io/pyroscope#667]
I'm running v0.5.1, and the `base-url` changes seem to be largely working (thanks!).
The only problem I've run into so far is that selecting tags yields a `404` since it is not using the base URL.

I believe the bug is here:
https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/redux/actions.js#L444-L462

![tags](https://user-images.githubusercontent.com/373762/147945719-3359fe9f-ffd8-45ef-ace4-ce3f6395e5f0.png)

**Comment by eh-am** [comment]
Should be solved via https://github.com/pyroscope-io/pyroscope/pull/676?
