### ISSUE TITLE
Create Kubernetes Manifest for Running All Examples in Kubernetes Cluster

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#697]
### Background
Currently we have a "demo" page located at https://demo.pyroscope.io. In order to create this demo page we took several popular "example" projects and added Pyroscope continuous profiling to these projects:
- [Google Microservices demo](https://github.com/GoogleCloudPlatform/microservices-demo)
- [Jaeger (hotrod)](https://github.com/pyroscope-io/hotrod-golang)
- etc

Then we send all of their profiling data to a single Pyroscope instance which we then expose at https://demo.pyroscope.io. 

While this was fine as we were just beginning and we didn't have any home-made examples to use, the major problem with this is the disconnect between what we show on the demo website and the source code that produced those profiles. Someone coming in with no prior knowledge will be very lost when they see our app dropdown which currently looks like this on the demo page:
![image](https://user-images.githubusercontent.com/23323466/148839968-64bd2291-9b08-4385-8718-7616af2fe81c.png)

Here are all of the problems with the current state of our demo (and its disconnect to our examples):
- There is no way for someone to see the source code which produced the profiles (important context to have) 
- There are so many example applications in this dropdown that it's hard to distinguish which applications are in which languages
- As we start to add more applications this will only become more unorganized and harder to quickly see information relevant to a particular potential pyroscope user
- We are using examples that contain code which we did not write... As we release new features (i.e. tags) it's much harder for us to edit existing projects examples as opposed to just using our own (see our [Python](https://github.com/pyroscope-io/pyroscope/tree/main/examples/python), [Go](https://github.com/pyroscope-io/pyroscope/tree/main/examples/golang-push/rideshare), and [Ruby](https://github.com/pyroscope-io/pyroscope/tree/main/examples/ruby) tags examples)

### Goal
we now have a fairly extensive set of examples in Pyroscope's [examples folder](https://github.com/pyroscope-io/pyroscope/tree/main/examples) and we would like to make a much more organized "examples" page where people can:
- Find the examples for the particular language / integration that they would like to learn more about
- See a direct link to the source code
- See a direct link to any blog / video materials related to that example 
- Contribute to the example

### Solution
In order to achieve all the goals listed above, here is how we would like to restructure / reorganize our examples. Ultimately we would like to have a single page -- a sort of "directory" which will allow people to see a much "cleaner" demo for a particular integration. The page will look something like this:
![pyroscope_examples_mockup_00-01](https://user-images.githubusercontent.com/23323466/148840901-8b118b05-ffd4-46ab-b02b-2f02f6cb7e0c.png)

Notice how there is a component for each specific example with links to all of the relevant information for that particular example:
- link to demo
- link to integration blog post
- link to integration video walkthrough
- link to pyroscope documentation
- link to source code for the example 

What we'd like to build in order to make this work in a (somewhat) simplistic way is a kubernetes cluster which reuses the `docker-compose.yml` files in each example folder and exposes the resulting pyroscope server for each example at example-specific routes:

- golang-push.demo.[hostname]
- golang-pull.demo.[hostname]
- ebpf.demo.[hostname]
- grafana-plugin.demo.[hostname]
etc..

**Comment by petethepig** [comment]
Reminds me of this page https://www.bugsnag.com/platforms

**Comment by eh-am** [comment]
>There are so many example applications in this dropdown that it's hard to distinguish which applications are in which languages

For this we had an idea that's orthogonal to this, but can help a little bit. And it's easy to implement (just base off `spy` name)

![image](https://user-images.githubusercontent.com/6951209/152014608-dfbe3221-c6a9-42fb-b1f2-bbc30995f0ca.png)


> There is no way for someone to see the source code which produced the profiles (important context to have)
With the sqlite database we can add metadata to specific applications?

**Comment by Rperry2174** [comment]
FYI goal is to **replace** -- current demo.pyroscope.io eventually

**Comment by Rperry2174** [comment]
Another example of potential layout:

I like this one because unlike the initial example you don't have to leave the page to access the resource
https://developer.confluent.io/get-started/dotnet
![2022-03-07 17 06 21](https://user-images.githubusercontent.com/23323466/157145473-d5922a3c-fb25-4dd0-afc6-b7648429cae4.gif)

**Comment by eh-am** [comment]
I had a look at `kompose` and the helm chart it generates is quite lackluster.

In that way I don't have a good solution that's written in docker-compose format and deployed to k8s.

We could create our own DSL, which would be translatable to docker-compose AND to k8s. But then if people want to run it, it becomes more complicated. Or we always generate these (docker-compose, helm chart) manually (from a DSL), risking them getting out of date.

**Comment by Rperry2174** [comment]
@petethepig Didn't you make some progress here? Could you give an update if so?
