### ISSUE TITLE
write: broken pipe

### ISSUE THREAD

**Issue by sujit-baniya** [pyroscope-io/pyroscope#70]
Out of  requests (on local), one request end up with write: broken pipe

ERRO[0263] Error happened when uploading a profile:Post "http://localhost:4040/ingest?from=1613035910&name=Verify+Rest&sampleRate=100&spyName=gospy&until=1613035920": write tcp 127.0.0.1:58206->127.0.0.1:4040: write: broken pipe 

And another error:
ERRO[0453] Error happened when uploading a profile:Post "http://localhost:4040/ingest?from=1613036100&name=Verify+Rest&sampleRate=100&spyName=gospy&until=1613036110": EOF

**Comment by petethepig** [comment]
Do most requests succeed, or does every single one fail?

**Comment by sujit-baniya** [comment]
@petethepig Most of the request succeed.. and some are failed (I would say every 5 or 10 request, above error occurs

**Comment by Issif** [comment]
I've same issue, and for all uploads:

```
ERRO[0029] Error happened when uploading a profile:Post "http://localhost:4040/ingest?from=1613826350&name=falcosidekick&sampleRate=100&spyName=gospy&until=1613826360": EOF 
```

**Comment by petethepig** [comment]
I think intermittent issues were fixed by #87.

**Comment by sujit-baniya** [comment]
@petethepig Still there are these issues:

```go
ERRO[0091] Error happened when uploading a profile:Post "http://localhost:4040/ingest?from=1614087850&name=Verify+Rest&sampleRate=100&spyName=gospy&until=1614087860": EOF 
```

**Comment by petethepig** [comment]
@sujit-baniya  Are you using the latest version? we just released one

**Comment by sujit-baniya** [comment]
@petethepig Yes I pulled latest docker image for server and latest agent for app
