### ISSUE TITLE
Keep existing colors when highlighting in diff page

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#700]
![image](https://user-images.githubusercontent.com/6951209/148975518-fef9b750-9750-4780-a36c-7355e9bc3c8c.png)

It doesn't make sense showing the classic green, since in diff mode you want to see how much that specific node changed, which is displayed via the node color.

**Comment by eh-am** [comment]
Now that I am thinking, we could apply this same logic everywhere:

When highlighted mode is ON
* Should this node be highlighted? 
  * if no, color it grey
  * if yes, color it with whatever color you were using anyway

That will work for comparison AND also for the other pages. 


Thoughts @Rperry2174 ?

**Comment by Rperry2174** [comment]
I definitely think keeping their natural colors looks better and is more useful
