### ISSUE TITLE
Add border to highlighted row in profiler table

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#706]
For reference see https://github.com/pyroscope-io/pyroscope/pull/701

Currently
![image](https://user-images.githubusercontent.com/6951209/149014178-f570304c-8ec2-4c48-b764-c887eace7a71.png)

Ideally:
![image](https://user-images.githubusercontent.com/6951209/149014236-eabb0720-cea3-466b-8f81-6e9b2ba9d662.png)

**Comment by ruslanpascoal2** [comment]
I'm tackling this one

**Comment by Rperry2174** [comment]
As we highlight the row we no longer need this
