### ISSUE TITLE
Don't allow querying in the future

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#722]
This is a regression.

Querying to a future date should not be possible.

https://user-images.githubusercontent.com/6951209/149400521-4e279d44-0776-4d4c-b7f4-0f7f84be245e.mp4

**Comment by naftalimurgor** [comment]
Hello @eh-am 

Seems like an issue I can work on. Let me know what I might need to get started with.

Regards,

Naftali

**Comment by eh-am** [comment]
Hey @naftalimurgor, it's all yours!

**Comment by Rperry2174** [comment]
hey @naftalimurgor are you still planning on picking up this issue?

**Comment by naftalimurgor** [comment]
Hello @Rperry2174 

Greetings! Sorry been quite busy. I'm working on this issue currently and will submit a PR as soon as it's ready. 

Thank you

**Comment by Rperry2174** [comment]
No worries just checking :) We appreciate the help! Let us know if you have any implementation questions (either here or on slack: https://pyroscope.io/slack)

**Comment by naftalimurgor** [comment]
Hey @Rperry2174 

Greetings! I'm on a slightly older Ubuntu distro, Ubuntu 16.0.4 I've set up the project as documented here [Devleopoer Guide](https://pyroscope.io/docs/developer-guide/).  
My question is, how do I visit the application on a web page. I can't seem to be able to visit the application after running `make dev` 

A portion of the output on the terminal with someports

```bash
goreman -exit-on-error -f scripts/dev-procfile start
23:42:01                air | Starting air on port 5000
23:42:01            webpack | Starting webpack on port 5100
23:42:01 webpack-standalone | Starting webpack-standalone on port 5200
23:42:01                air |   __    _   ___  
23:42:01                air |  / /\  | | | |_) 
23:42:01                air | /_/--\ |_| |_| \_ v1.12.1 // live reload for Go apps, with Go1.14.0
23:42:01                air | `.air.conf` will be deprecated soon, recommend using `.air.toml`.
23:42:01                air | watching .
23:42:01                air | !exclude benchmark
23:42:01                air | watching cmd
23:42:01                air | watching cmd/pyroscope
23:42:01                air | watching cmd/pyroscope/command
23:42:01                air | !exclude cypress
23:42:01                air | watching dist
23:42:01                air | watching dist/standalone
23:42:01                air | watching dockerfiles
```

Thank you

**Comment by Rperry2174** [comment]
Hey @naftalimurgor I don't see any error here. Did you visit http://localhost:4040 on your machine?

**Comment by naftalimurgor** [comment]
Hello @Rperry2174 

Perhaps I missed something. I tried http://localhost:4040 and it still doesn't work. Here's a gist of the output: https://gist.github.com/naftalimurgor/d88e0a4e5f9bde4d9e002510cdd81825

**Comment by Rperry2174** [comment]
Hey @naftalimurgor I'm going to remove some of these comments to keep this issue clean. From looking at the [error message](https://gist.github.com/naftalimurgor/d88e0a4e5f9bde4d9e002510cdd81825) it looks like you're missing some installations that you need (i.e. `cargo not found`) 

```
slax@murgor:~/go/src/pyroscope$ make build-third-party-dependencies
cd third_party/rustdeps && RUSTFLAGS="-C relocation-model=pic -C target-feature=+crt-static" cargo build --release --target "x86_64-unknown-linux-gnu" || make print-deps-error-message
/bin/sh: 1: cargo: not found
make[1]: Entering directory '/home/slax/go/src/pyroscope/third_party/rustdeps'
make[1]: *** No rule to make target 'print-deps-error-message'.  Stop.
make[1]: Leaving directory '/home/slax/go/src/pyroscope/third_party/rustdeps'
Makefile:121: recipe for target 'build-rust-dependencies' failed
make: *** [build-rust-dependencies] Error 2
```

I'm going to delete some messages from this thread, but if you try to install the missing packages from the output here and it still doesn't work can you create a separate issue to address this?

**Comment by naftalimurgor** [comment]
hell @eh-am @Rperry2174 

Greetings! I opened a pull request to address this issue here: https://github.com/pyroscope-io/pyroscope/pull/875

**Comment by eh-am** [comment]
Closing as per https://github.com/pyroscope-io/pyroscope/pull/875#pullrequestreview-888628706
