### ISSUE TITLE
feat: pyroscope-pannel  use flipcard to display  the flamegraph and table view

### ISSUE THREAD

**Issue by linthan** [pyroscope-io/pyroscope#727]
![image](https://user-images.githubusercontent.com/13914829/149509972-c1db8965-0cea-464b-8d7d-473a2dfb277c.png)

flipcard demo:
http://mzabriskie.github.io/react-flipcard/basic/
https://edwardorz.github.io/vue-flipcard/

**Comment by eh-am** [comment]
Great point! We were considering bridging the existing [grafana table visualization](https://grafana.com/docs/grafana/latest/visualizations/table/). But it makes sense using our own, which will definitely have more features, like https://github.com/pyroscope-io/pyroscope/pull/701

**Comment by linthan** [comment]
related to pyroscope-pannel ,there are no extra space to display both flamegraph and table view.  
grafana is a better way to integrate many pyroscope datasources. using the native pyroscope ui interface for us is a little incovenient.
![image](https://user-images.githubusercontent.com/13914829/149602945-6145c7ae-c21b-4b06-b0a1-12723956be94.png)

**Comment by linthan** [comment]
related to pyroscope-pannel ,there are no extra space to display both flamegraph and table view.  
grafana is a better way to integrate many pyroscope datasources. using the native pyroscope ui interface for us is a little incovenient.
![image](https://user-images.githubusercontent.com/13914829/149602945-6145c7ae-c21b-4b06-b0a1-12723956be94.png)

**Comment by eh-am** [comment]
We now support different views! https://github.com/pyroscope-io/grafana-panel-plugin/releases/tag/v1.4.1
