### ISSUE TITLE
feat: support  serve_from_sub_path mode like grafana 

### ISSUE THREAD

**Issue by linthan** [pyroscope-io/pyroscope#734]
we need use many pyroscope instances  to share pressure of scraping data.  In order to use pyroscope native ui in a uniform way, we need a better way to emmbed pyroscope ui into other mature platform, so we need the pyroscope's   ability of  serve_from_sub_path  like grafana.

![image](https://user-images.githubusercontent.com/13914829/149688300-4df97a5e-8af3-4345-bd02-06ffb22f93d9.png)

**Comment by petethepig** [comment]
We do have support for that, check out `--base-url` flag for that. We also have a PR for adding an example for this feature [here](https://github.com/pyroscope-io/pyroscope/pull/710/files)

@linthan Let me know if you have any questions about it or if there's some use-cases our implementation doesn't support.

**Comment by linthan** [comment]
@petethepig  it doesn't work well.
![image](https://user-images.githubusercontent.com/13914829/149695844-40ae0791-ec39-4ce8-8ab6-d90f8782433a.png)

**Comment by linthan** [comment]
@petethepig  it works.  thx a million
