### ISSUE TITLE
Java 7 support for Pyroscope Java Agent

### ISSUE THREAD

**Issue by netamego** [pyroscope-io/pyroscope#747]
Hi,

Pyroscope is amazing!!! I use it in java 1.8 apps without problems and the use of asyc-profiler was the best aproach that could be taken.

My problem is that I have a lot of apps in Java 1.7 and I can't compile Pyroscope Java Agent for Java 1.7 version because two files in source code use "lambda expressions" and "method references" that are not supported in Java 1.7

Could be possible to make Java Agent source code compatible with java 1.7?

Thank you very much.

This is the output from "./gradlew shadowJar"

```
> Task :agent:compileJava FAILED

/opt/pyroscope-java-0.4.1/agent/src/main/java/io/pyroscope/javaagent/EventType.java:42: error: lambda expressions are not supported in -source 7
            .filter(eventType -> eventType.id.equals(id))
                              ^
  (use -source 8 or higher to enable lambda expressions)


/opt/pyroscope-java-0.4.1/agent/src/main/java/io/pyroscope/javaagent/EventType.java:44: error: method references are not supported in -source 7
        return maybeEventType.orElseThrow(IllegalArgumentException::new);
                                                                    ^
  (use -source 8 or higher to enable method references)


/opt/pyroscope-java-0.4.1/agent/src/main/java/io/pyroscope/javaagent/PyroscopeAgent.java:48: error: lambda expressions are not supported in -source 7
            final Runnable dumpProfile = () -> {
                                            ^
  (use -source 8 or higher to enable lambda expressions)


3 errors

```

**Comment by Rperry2174** [comment]
hey @netamego thanks for reporting this and glad you're enjoying using Pyroscope. We'll look into what it would take to make it compatible with 1.7 but not sure what the timeline will be on this. We'll report back here as we make progress!

**Comment by netamego** [comment]
Thank you very much @Rperry2174 it is a pity. Async-profiler , used by the pyroscope java agent, supports java 1.7 so I understand that pyroscope java agent should support it as well. There are a lot of apps in java 1.7. In any case, I understand that this request is not a priority. Thank you very much for the great work you are doing and for answering so quickly.

**Comment by korniltsev** [comment]
Semi-fixed in https://github.com/pyroscope-io/pyroscope-java/issues/10
