### ISSUE TITLE
Application search improvements

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#758]
https://user-images.githubusercontent.com/6951209/150854215-ed0908bc-ce2e-4dd4-8790-9da80e3038a7.mp4

Would be nice to have the input fixed to the top, even when you scroll. That allows you to peek into the existing values, and quickly filter to what you want, without requiring to scroll back to the top.

* [ ] fix the input to the top (even when scrolling)
* [ ] focus on the input field on app click
* [ ] fuzzy match

**Comment by petethepig** [comment]
I was also thinking, the moment you click on the application name it should focus on the input field (right now you have to manually click on it)

And it would also be cool if search was fuzzy, e.g when you type `catalogcpu` it would show you `catalog.service.go.cpu`

**Comment by adi611** [comment]
Please assign me this issue.

**Comment by Rperry2174** [comment]
Hey @adi611 thanks for taking a look going to unassign for now in case someone else wants to give this a shot
