### ISSUE TITLE
Wrong flame graph when use API

### ISSUE THREAD

**Issue by netamego** [pyroscope-io/pyroscope#767]
Hi,

I have profiled a java app with async-profiling using next command:

`async-profiler/profiler.sh -e itimer -d 10 -o collapsed -f profiler.collapsed 25294`

Next I have converted profiler.collapsed to profiler.html flamegraph with next command:

`java -cp async-profiler/build/converter.jar FlameGraph profiler.collapsed  profiler.html`

On the other hand I have uploaded profiler.collapsed to pyroscope with next command:

`start=$(date +"%s") && sleep 5 && end=$(date +"%s") && curl -vvv -k -X POST "http://myserver.test:4040/ingest?name=testapi.itimer&units=samples&aggregationType=sum&sampleRate=100&from=${start}&until=${end}&spyName=javaspy" -d @profiler.collapsed`

The flame graphs should be the same but this is the flame graph from async-profiler:

![image](https://user-images.githubusercontent.com/10206580/151195356-00bc7f26-479f-4319-8043-87bacdaf49ed.png)

And this one from pyroscope. 

![image](https://user-images.githubusercontent.com/10206580/151195619-ed9c99a6-1230-4f41-b509-68c7de77d2b6.png)

I have cutted off the pyroscope flamegraph screenshot because all stack is in one colum and it's too large.

The concern is that the API is used with other agents such as the java agent. Will the same thing happen with agents?

I have attached profiler.collapsed file (sorry but github only supports zip) in case you want to do some test.

[profiler.zip](https://github.com/pyroscope-io/pyroscope/files/7943100/profiler.zip)

Thank you.

Best regards.

**Comment by netamego** [comment]
Hi

I'm pretty sure I'm misunderstanding something.

I have teted the example in [documentation](https://pyroscope.io/docs/server-api-reference).

```
cat profiler.collapsed
func1;func2 100
func1;func3 200
```

I have tested async-profiler flamegraph

`java -cp async-profiler/build/converter.jar FlameGraph profiler.collapsed profiler.html`

The flamegraph from async-profiler makes sense for me:

![image](https://user-images.githubusercontent.com/10206580/151247033-0437e349-7ef8-4b35-9c8e-3972240fe17f.png)

We can see func1 bar and in top of it two separate bars. One for func2 and other for func3. func3 bar is wider because have more samples.

Then, I did:

`start=$(date +"%s") && sleep 0.5 && end=$(date +"%s") && curl -vvv -k -X POST "http://myserver.test:4040/ingest?name=testapi.itimer&from=${start}&until=${end}" -d @profiler.collapsed`

and the flamegraph is:

![image](https://user-images.githubusercontent.com/10206580/151247429-4778a6da-aca6-47e2-a823-9e68890b6b47.png)

which have no sense for me. And what about "2 seconds"? Why "2 seconds" when from start and end ikeys in POST have elapsed 500ms?

Thanks a lot.

**Comment by netamego** [comment]
Hi 

My mistake.

If i do:

`start=$(date +"%s") && sleep 0.5 && end=$(date +"%s") && cat profiler.collapsed | curl -vvv -X POST --data-binary @- "http://myserver.test:4040/ingest?name=testapi.itimer&from=${start}&until=${end}"`

instead of:

`start=$(date +"%s") && sleep 0.5 && end=$(date +"%s") && curl -vvv -k -X POST "http://myserver.test:4040/ingest?name=testapi.itimer&from=${start}&until=${end}" -d @profiler.collapsed`

flamegraph is correct and i can POST without problems stacks obtained with:

`async-profiler/profiler.sh -e itimer -d 10 -o collapsed -f profiler.collapsed 25294`

Sorry for open this.

Best regards.

**Comment by Rperry2174** [comment]
No need to apologize @netamego ! Glad you we're able to get it to work. FYI we've started looking into fixing/closing out more of our java issues. Appreciate you reporting these as they come up!
