### ISSUE TITLE
Fix plural of datepicker

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#778]
![image](https://user-images.githubusercontent.com/6951209/151679882-54daa4ae-d97b-4fac-8a29-d03f28ef0585.png)
Should be `Last 1 hour`

**Comment by louisphn** [comment]
May I help you with this issue? :raising_hand:

**Comment by Rperry2174** [comment]
Hey @louisphn feel free to pick this up! We'll assign to you once you open the pr. Thanks for the help!

**Comment by louisphn** [comment]
> Hey @louisphn feel free to pick this up! We'll assign to you once you open the pr. Thanks for the help!

Actually I think I will drop off the task here because I did not notice that most of the code is developed in Go and made a mistake thinking that this is Typescript project. I am extremely sorry for the inconvenience and hope for your understanding.

**Comment by Preetmungara** [comment]
> This is a typescript implementation though! I believe the component related to this issue is https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/DateRangePicker.jsx

Hey, I can see there is already "Last 1 hour" written in code already. so where change needs to be done?

**Comment by eh-am** [comment]
Figuring why that's not working is part of the task :)

My hunch is that we are just using whatever `range` is set https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/DateRangePicker.jsx#L56, which comes from `CustomDatePicker`
https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/CustomDatePicker.tsx#L42

So it looks like the problem is with 
https://github.com/pyroscope-io/pyroscope/blob/7751b1562194eafa21fc77e3601c4a525250c31c/webapp/javascript/util/formatDate.ts#L43

However, the test says that the implementation is correct https://github.com/pyroscope-io/pyroscope/blob/7751b1562194eafa21fc77e3601c4a525250c31c/webapp/javascript/util/formatDate.spec.ts#L10

The bug is lurking somewhere there. It requires a bit of investigation.

**Comment by louisphn** [comment]
I think the bug is here where object values are fixed as plural nouns. I am having issue with setting up the local development environment so I will fix this as soon as I can have the environment working:
https://github.com/pyroscope-io/pyroscope/blob/26d817746078ffef2059560552cac0e45495182c/webapp/javascript/util/formatDate.ts#L4-L14

Possible way to fix this could be conditional rendering here:
https://github.com/pyroscope-io/pyroscope/blob/26d817746078ffef2059560552cac0e45495182c/webapp/javascript/util/formatDate.ts#L43-L48

```js
   if (/^now-/.test(from) && until === 'now') { 
     const { number, _multiplier } = convertPresetsToDate(from); 
     return `Last ${number} ${number >= 2 ? _multiplier : _multiplier.slice(0, -1)}`; 
   } 
```
or cleaner by splitting it to another line:
```js
   if (/^now-/.test(from) && until === 'now') { 
     const { number, _multiplier } = convertPresetsToDate(from); 
     const multiplier = number >= 2 ? _multiplier : _multiplier.slice(0, -1)
     return `Last ${number} ${multiplier}`; 
   } 
```
