### ISSUE TITLE
Move pages from Go templates to react

### ISSUE THREAD

**Issue by kolesnikovae** [pyroscope-io/pyroscope#802]
At the present time, pyroscope server renders some pages (https://github.com/pyroscope-io/pyroscope/tree/main/webapp/templates) from Go templates. We should move this to react. This will also require us to extend HTTP API to expose some info required to the UI (like which authentication options are available, build version and so on.)

This is a pre-requisite for https://github.com/pyroscope-io/pyroscope/issues/803

**Comment by petethepig** [comment]
Trying to break this down a bit, I'm thinking the steps could be something like this:
* [ ] make the pages render in react
* [ ] on the frontend, add support for detecting if the user logged in or not
* [ ] on the backend, implement login functionality, etc
* [ ] on the backend, replace redirects with some json responses I assume
* [ ] connect the frontend to these new backend apis

---

It's also important to make sure oauth still works after this.

**Comment by kolesnikovae** [comment]
Thank you @petethepig, the plan looks good.

As far as the change affects both FE and BE, I think we need to establish the contract first of all: what API calls should be done by FE and when, what are the inputs and outputs (more specifically: HTTP codes, JSON payload, error handling).

FE has to know some server settings and properties (like [which authentication options are available](https://github.com/pyroscope-io/pyroscope/blob/ac1fdd277e61dbe21ae95dd9036eeb7cbd85ffc3/pkg/server/login.go#L44-L50), build version and [so on](https://github.com/pyroscope-io/pyroscope/blob/ac1fdd277e61dbe21ae95dd9036eeb7cbd85ffc3/pkg/server/handler.go#L119-L128)) to render pages properly.

Note that this info is to be available to everyone, therefore we should be very careful disclosing server details (see [CWE-200](https://cwe.mitre.org/data/definitions/200.html)). We should also come up with a solution for user notifications – as for now we embed them into the generated pages: https://github.com/pyroscope-io/pyroscope/blob/ac1fdd277e61dbe21ae95dd9036eeb7cbd85ffc3/pkg/server/handler.go#L119-L128 

Therefore it makes sense to split it into independent endpoints:
- `GET /api/server/auth-settings` (available to everyone) - authentication options required to FE exclusively. Similar to what is [rendered in the login handler](https://github.com/pyroscope-io/pyroscope/blob/ac1fdd277e61dbe21ae95dd9036eeb7cbd85ffc3/pkg/server/login.go#L45-L50).
- `GET /api/server/version` (protected) - build info, enabled features, etc. We already [have this endpoint](https://github.com/pyroscope-io/pyroscope/blob/ac1fdd277e61dbe21ae95dd9036eeb7cbd85ffc3/pkg/server/build.go#L9) available under (`/build`).
- `GET /api/server/notifications` (protected) - returns all the available server notifications (should it be available to admins only?).

**Comment by eh-am** [comment]
Bit tangential but wouldn't it make sense to version these new APIs?

RE variables, I think we are mixing things. I don't think we are moving everything to React yet, since that's a bit more complicated.
My understanding is that we are only rendering these login pages in React, and therefore we can assume these [server variables](
https://github.com/pyroscope-io/pyroscope/blob/ac1fdd277e61dbe21ae95dd9036eeb7cbd85ffc3/pkg/server/handler.go#L119-L128) will be available under the global `window` object.

**Comment by kolesnikovae** [comment]
> Bit tangential but wouldn't it make sense to version these new APIs?

I'd say, we may want, though there is no apparent reason. More detailed answer here: https://github.com/pyroscope-io/pyroscope/issues/869#issuecomment-1048100833.

> RE variables, I think we are mixing things. I don't think we are moving everything to React yet, since that's a bit more complicated.
> My understanding is that we are only rendering these login pages in React, and therefore we can assume these [server variables](https://github.com/pyroscope-io/pyroscope/blob/ac1fdd277e61dbe21ae95dd9036eeb7cbd85ffc3/pkg/server/handler.go#L119-L128) will be available under the global window object.

We need to move all the pages eventually (except ones related to OAuth, I think). The actual point of this issue (apart from the refactoring) is to make UI to handle user requests before the server in order to implement authentication refresh tokens with rotation: https://github.com/pyroscope-io/pyroscope/issues/803.

For example: when user visits, say, `/` and their token expired, a new access token should be requested by FE without forcing user to login again. Currently it is not possible (in a trivial way) because the server handles `/` and can only redirect a user to the login page if the tokes has expired. Instead, the server should only handle assets, API, and diagnostic endpoints. Any other request should be handled by SPA.

But I think we can split the change into parts:
 - login and signup pages
 - [index](https://github.com/pyroscope-io/pyroscope/blob/ac1fdd277e61dbe21ae95dd9036eeb7cbd85ffc3/pkg/server/handler.go#L19-L51) _pages_
 - (optional) remaining (redirect, welcome, forbidden)

**Comment by Rperry2174** [comment]
This is pretty much finished right @shaleynikov ? I think there might be one page left?
