### ISSUE TITLE
tagged span -> profile_id profiles should not disappear from whole process view

### ISSUE THREAD

**Issue by lizthegrey** [pyroscope-io/pyroscope#818]
thread-tagged data that's being stored in a bespoke profile_id should also still be indexed under its parent process, so that you don't see weird drops like this in the timeline from when all but the background work gets removed from the service/process tags:

https://share.getcloudapp.com/DOum1RYX

**Comment by petethepig** [comment]
@kolesnikovae this is basically that multiplexing thing we talked about
