### ISSUE TITLE
Discard insignificant pprof profile samples at parsing

### ISSUE THREAD

**Issue by kolesnikovae** [pyroscope-io/pyroscope#823]
Discard insignificant pprof profile samples at parsing: avoid allocations and decrease tree size. It was observed that some profiles (e.g Go pprof heap) can include very high number of samples, meanwhile we only keep 2k tree nodes.

Note that the text below mentions impact on CPU consumption. Meanwhile, there is considerable GC overhead. We should revisit this idea taking into account all the factors and consequences. Cumulative profiles are the largest ones (Go heap alloc_object, alloc_space).

See https://github.com/pyroscope-io/pyroscope/pull/663 Failed attempts No. 1:

---

The experiment has not shown any significant improvements in practice, despite very promising benchmarks:
```
BenchmarkProfile/Read-4     45	  22720437 ns/op	 1886226 B/op	   40638 allocs/op
BenchmarkProfile/ReadX-4   130	   8792172 ns/op	  479494 B/op	   10100 allocs/op
```
<img width="701" alt="image" src="https://user-images.githubusercontent.com/12090599/148384071-b1da79b7-13ae-4360-bf72-3ce718189d41.png">
Similar impact on allocated objects. Taking into account that the change may cause notable loss of precision, I decided to exclude it from the set. Probably, we should revisit it again separately.

**Comment by Rperry2174** [comment]
i believe @petethepig addressed this feel free to reopen if not
