### ISSUE TITLE
Add usability improvements to app dropdown selector

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#827]
Currently the app dropdown selector can get a little long for users who have many apps. The most common issue is that the app dropdown will default to the same app every time, which my not be the app that a user is most interested in viewing. 

Interested in getting other opinions, but two ideas that I have for this are:

## Idea 1: Add persistence to app selector dropdown
Add some kind of persistence that will default to the _last app_ that was viewed in Pyroscope 

## Idea 2
Add a "last viewed apps" array similar to this
![image](https://user-images.githubusercontent.com/23323466/153481991-61daa5a3-00a9-40e2-bda8-b31f307ce45c.png)

Or similar to most browsers where your most visited sites tend to show up higher in the list... That being said, would be interested in others opinions here if they have any. 

## Idea 3: Favoriting apps
Another Idea is to be able to "favorite" apps and have them show up higher in the list than the rest of the apps

## Idea 4: Combining app dropdown and tag selector
Another idea is to remove the "application" dropdown altogether and go with a design more similar to this:
![image (35)](https://user-images.githubusercontent.com/23323466/153482662-d39922b2-a653-4224-b98e-3af202b5683e.png)

where applications and tags are all treated similarly and selected in the same dropdown

**Comment by abeaumont** [comment]
I think ideas 1, 2, and 3 work well for one use case, when the user wants to see an overview of the key metrics. In this case, the usage pattern is more or less the same over time, so having favs or last used apps is useful.

There's another use case that is not well covered by these ideas, which is the exploratory use case. In those use case, users want to make specific queries, maybe queries that have been never used before / will never be used later, but they still want to make them quickly (e.g. this may happen during an incident). For this use case, I'd like to add another idea:

## Idea 5: Query field with application and tag autocompletion.

Currently, the application selection has an input field that has application autocompletion.
There's also a query field that allows to write both application and tags, but doesn't support autocompletion.
Merging both together would give much more power to the query field, and giving it the focus by default would make it pretty quick to write those queries. Here's a rough sketch of how application dropdown, tag dropdown and query field could be put closer together (this mock-up is not needed for the idea):

![pyroscope-query](https://user-images.githubusercontent.com/80059/153582690-aa321bfb-9a54-42bf-8ec0-9a25fde60f85.png)

I think Idea 4 is orthogonal to the rest of the ideas, and it could be implemented independently. I think it'd work fine with Idea 5 too.

**Comment by Rperry2174** [comment]
I actually meant the same thing as what you mentioned in combining the two with idea 4...

**Comment by Rperry2174** [comment]
closing from #1199 we may still make some of these improvements but should be a new issue if so
