### ISSUE TITLE
Document the agent protocol

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#83]
Multiple people asked for this in both slack and twitter, We need to write something about it soon.

**Comment by petethepig** [comment]
This kinda depends on #28 because right now we control the client and it always sends data in 10 second chunks. We need to confirm the storage part won't break if you start sending data for arbitrary time periods.

**Comment by YangKeao** [comment]
Yes. As the author of a simple rust profiler ([`pprof-rs`](https://github.com/tikv/pprof-rs)), I cannot wait to integrate it with a continuous visualizer :mechanical_arm:  .

**Comment by petethepig** [comment]
@YangKeao This is the next thing on my TODO list after #7
