### ISSUE TITLE
Newer version available not working properly

### ISSUE THREAD

**Issue by abeaumont** [pyroscope-io/pyroscope#835]
As can be seen in the [demo site](https://demo.pyroscope.io/), it's currently using v0.10.0 and it has a message saying that a newer version is available (v0.9.0):

![newer-version-available](https://user-images.githubusercontent.com/80059/153865191-9d34b823-facd-4b8e-ac92-1358171178e4.png)

**Comment by eh-am** [comment]
We can try checking the latest version more often?
