### ISSUE TITLE
Saving user profile sends empty fullName to backend

### ISSUE THREAD

**Issue by shaleynikov** [pyroscope-io/pyroscope#850]
While it shouldn't send it at all

Steps to reproduce:
1. Enable basic auth
2. Go to profile editing
3. Erase contents of fullName
4. Push Save

fullName wouldn't be deleted as expected.

**Comment by Rperry2174** [comment]
closed in https://github.com/pyroscope-io/pyroscope/pull/868/commits/3088970e6e28b56ab4ff8541788360b2c2abde98
