### ISSUE TITLE
When sharing to flamegraph.com we should include a name

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#853]
Right now when you click the "flamegraph.com" button in the share tab it will get a shareable link. we should make it so that the app name is included as well:

So this:
![image](https://user-images.githubusercontent.com/23323466/154151356-6840a4fd-22d0-4dda-81ee-38ea674e2f39.png)

Should be the equivalent of (note profile name at the bottom):
![image](https://user-images.githubusercontent.com/23323466/154151178-0e5bb70b-47c5-4cb1-9a41-84605fdfe8d0.png)

Or at the very least a generic `name` field should be passed along

**Comment by eh-am** [comment]
It's being sent, the problem is with flamegraph.com that is not using it.

![image](https://user-images.githubusercontent.com/6951209/154277008-643f88fc-df40-4f23-8ac9-44eec48d5dd6.png)
