### ISSUE TITLE
Bad table contrast

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#858]
![image](https://user-images.githubusercontent.com/6951209/154275573-1143baae-3663-4eb0-8c52-818537627ef1.png)

It seems white doesn't work really well against these colors.

**Comment by ACENSONIX** [comment]
I would like to work on this.

**Comment by eh-am** [comment]
@ACENSONIX Awesome! It's all yours!

**Comment by ACENSONIX** [comment]
Yes this is my first time contributing so right now I am just trying to figure out how this project works. It will take some time for me to figure it out. I hope that is fine.
