### ISSUE TITLE
Error 404 for Golang code examples

### ISSUE THREAD

**Issue by naftalimurgor** [pyroscope-io/pyroscope#867]
Hello @eh-am 

I can't seem to find code examples for Golang after visiting the link provided in the main README.md documentation here:https://github.com/pyroscope-io/pyroscope#example-code for Golang which points to a 404 page here: https://github.com/pyroscope-io/pyroscope/tree/main/examples/golang suggesting that it could be missing?

Thanks

**Comment by Rperry2174** [comment]
I just updated thanks @naftalimurgor

**Comment by naftalimurgor** [comment]
Great! I was trying to see how this works then I came across that. You are welcome!
