### ISSUE TITLE
Search doesn't highilight partial results properly

### ISSUE THREAD

**Issue by abeaumont** [pyroscope-io/pyroscope#870]
When searching for results, partial results are not highlighted:

![highlight](https://user-images.githubusercontent.com/80059/154663516-ad09f5aa-c11b-4439-8f1c-d44ff399c25e.png)

According to @eh-am, the problem seems to be that only an exact match works in the table https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/ProfilerTable.jsx#L257 instead any match as in https://github.com/pyroscope-io/pyroscope/blob/d95c185d3a31216a145bf3cd20470315a10e061d/webapp/javascript/components/FlameGraph/FlameGraphComponent/Flamegraph_render.ts#L389-L396

**Comment by eh-am** [comment]
Should be simple to solve. Ideally both `ProfilerTable` and `Flamegraph_render` would use the same matching function.

**Comment by abeaumont** [comment]
@eh-am just realized this is a duplicate of #748. Closing.
