### ISSUE TITLE
Refactor all css colors into global variables file

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#879]
We would like to better organize our CSS for two reasons:
1. We would like to have it be more organized
2. We would like to eventually do a "light" color theme instead of a dark color theme

In order to achieve these goals there are two initial steps that we need to take:
- [ ] Move all colors in _all_ css files into a global [variables.css](https://github.com/pyroscope-io/pyroscope/blob/main/webapp/sass/variables.scss)  file. Instead of referring to hard-coded colors we should refer only to variables in all css files moving forward. We will eventually refactor duplicates / similar colors into a slimmer set of variables
- [ ] Move most css from [profile.css](https://github.com/pyroscope-io/pyroscope/blob/main/webapp/sass/profile.scss) into the proper `[component].module.css` file. There will still be a few global styles here but the goal should be to make `profile.scss` as minimal as possible

There are definitely more steps that we'll need to take after this, but these will be the major first steps needed to be able to add an alternate color scheme

cc/ @eh-am feel free to add any more information here

**Comment by eh-am** [comment]
I think there are 2 parts here:

One is about the `FlamegraphRenderer` component itself. After https://github.com/pyroscope-io/pyroscope/issues/866 is implemented its colors will be stored independently from the main application.

Second is about the webapp itself, which is what this issue refers to.

**Comment by Rperry2174** [comment]
completed in #932
