### ISSUE TITLE
Improve the eBPF integration

### ISSUE THREAD

**Issue by abeaumont** [pyroscope-io/pyroscope#880]
Our current eBPF support can be improved in some areas, including:
- It's built on top of (python) bcc tools, which is thus a dependency.
- It periodically loads / unloads the the BPF program, which may cause some profiling precission loss.
- No support for BTF / CO-RE.

Some of these improvements may require higher minimal Linux kernel versions, to there are also some trade-offs to consider.

**Comment by petethepig** [comment]
Tentative plan:
* Get the python-less version of ebpfspy to run
* Get ebpfspy to run without compiling ebpf program each time
* Make ebpfspy work on old versions as well (without [CO-RE](https://nakryiko.com/posts/bpf-portability-and-co-re/)) https://github.com/aquasecurity/btfhub

**Comment by Rperry2174** [comment]
Improved see blog post [here](https://pyroscope.io/blog/ebpf-profiling-pros-cons/)
