### ISSUE TITLE
Remove redundant 'api key name can't be empty' message

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#905]
The message is shown in 2 places, which makes it redundant

![Peek 2022-03-02 11-09](https://user-images.githubusercontent.com/6951209/156377560-3480b1ac-5ac4-470c-8997-df50a4ef78dc.gif)

Plus it's not styled as if it were an error so it's even more confusing.

**Comment by webstradev** [comment]
Would it be beneficial to prevent making the request when the name is empty. 
Besides the fact that the error is duplicated and should be removed.

It seems like the type of bad request you would want to prevent from happening all together. 

A simple solution would be making the "Add API Key" button disabled until The name field has some input.

**Comment by eh-am** [comment]
>Would it be beneficial to prevent making the request when the name is empty.
Good point!

>Or just making the name field required so the form does not submit unless it has a value.
Let's go with this one, let the browser's required popup do the work for us.

**Comment by webstradev** [comment]
Sounds good I have added that to #917

**Comment by webstradev** [comment]
This can be closed I think

**Comment by eh-am** [comment]
Not happening anymore
