### ISSUE TITLE
Memory leak detection

### ISSUE THREAD

**Issue by wolfv** [pyroscope-io/pyroscope#92]
Hi,

pyroscope looks awesome! I am looking forward to use it to monitor / profile our server application.

I was wondering if pyroscope can also measure memory usage, and help debug memory leaks? Is that in scope / on the roadmap? 
Just curious, and feel free to close the issue.

**Comment by chadbrewbaker** [comment]
Modify the code to also log /proc/pid/status etc:
https://unix.stackexchange.com/questions/224015/memory-usage-of-a-given-process-using-linux-proc-filesystem

**Comment by petethepig** [comment]
We recently released [v0.0.30](https://github.com/pyroscope-io/pyroscope/releases/tag/v0.0.30) which comes with support for `inuse_objects` and `inuse_space` metrics in Go. Those are very useful for detecting leaks.
