### ISSUE TITLE
Focusing on a timeline with no items sends you back to 1969

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#934]
![Peek 2022-03-10 12-45](https://user-images.githubusercontent.com/6951209/157699018-5722aac8-5bdf-4085-b46e-274017bb3f12.gif)

Recommend waiting on https://github.com/pyroscope-io/pyroscope/pull/927 before working on this

**Comment by EgorMozheiko** [comment]
@eh-am
Seem to have found the cause of this issue:
Choosing timeline with no items sends right timestamps (from/until), but the response does not contain the "timeline" property, which causes the issue.


Request with time period **_containing items_**:
![image](https://user-images.githubusercontent.com/90687109/160880565-6a8c0993-dac4-41e5-bfd7-4c980369fc7c.png)
The response: 
![image](https://user-images.githubusercontent.com/90687109/160880757-722b564b-c94b-4ab8-9b97-92a05ec84321.png)


Request with time period **_containing no items_**:
![image](https://user-images.githubusercontent.com/90687109/160880863-51a9c1b0-7e37-4417-97f0-50851d61d0eb.png)
The response:
![image](https://user-images.githubusercontent.com/90687109/160880924-dfdd6984-d99a-40d5-8dc1-743602406a95.png)
