### ISSUE TITLE
Add a way to export flamegraph (and table) as image or pdf

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#96]
A lot of people have been asking for ways of how they can export the flamegraph data so that they can either save it or share it with other members of their org. We should add a button that allows users to export this data. Some things to consider:

1. Data should be able to export to image
2. Table also needs to be somehow converted to image
3. Potentially both should be able to send as a PDF

This is also one of the first steps to be able to add alerts

**Comment by petethepig** [comment]
This was implemented in #143
