### ISSUE TITLE
Add Frontend Support for annotations on timeline

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#97]
Most charting libraries have a way to annotate data. We should make it so that if you want to specifically annotate something special at a particular timestamp, that you can click on the timeline graph and add that annotation

![image](https://user-images.githubusercontent.com/23323466/186502103-d4cedb23-81ad-42a7-a8ec-edd9319c29ed.png)

**Comment by wusphinx** [comment]
> Most charting libraries have a way to annotate data. We should make it so that if you want to specifically annotate something special at a particular timestamp, that you can click on the timeline graph and add that annotation

It's better to show timestamp when I click on the timeline

**Comment by Rperry2174** [comment]
Here is how honeycomb's looks -- i like the little pin at the top:
![image](https://user-images.githubusercontent.com/23323466/150172444-dc82c411-a667-43b4-8b48-e8f3621e8e1f.png)
