### ISSUE TITLE
Dead Slack invite link on Pyroscope webpage and the software

### ISSUE THREAD

**Issue by dipanjan** [pyroscope-io/pyroscope#996]
The Slack invite link that is linked from the [Website](https://pyroscope.io) and included in the software is dead. Also, is there a Slack workspace for Pyroscope at the moment?

**Comment by petethepig** [comment]
@dipanjan Fixed it, thanks for reporting it!

**Comment by dipanjan** [comment]
I guess it will take some time for the change to reflect on the website. Can you please share the link here so that I can join?

**Comment by petethepig** [comment]
I see, yeah it might get cached.. Try this one: https://join.slack.com/t/pyroscope/shared_invite/zt-16e0qeww7-5M_kLPPkyqOelM_XKrPlVg
